load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "memory",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/common/mononoke_macros:mononoke_macros"],
    test_labels = ["serialize_test_cases"],
    deps = select({
        "DEFAULT": ["fbsource//third-party/rust:memory-stats"],
        "ovr_config//os:linux": ["fbsource//third-party/rust:procfs"],
    }),
)
