load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "memory",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/mononoke_macros:mononoke_macros"],
    test_labels = ["serialize_test_cases"],
    deps = [
        "fbsource//third-party/rust:memory-stats",
    ],
)
