load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "caching_ext",
    srcs = glob([
        "src/**/*.rs",
    ]),
    named_deps = {"bincode": "fbsource//third-party/rust:bincode-2"},
    test_deps = [
        "fbsource//third-party/rust:maplit",
        "fbsource//third-party/rust:quickcheck",
        "fbsource//third-party/rust:tokio",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:once_cell",
        "//common/rust/shed/cachelib_stub:cachelib",
        "//common/rust/shed/cloned:cloned",
        "//common/rust/shed/justknobs_stub:justknobs",
        "//common/rust/shed/memcache_stub:memcache",
        "//common/rust/shed/stats:stats",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
)
