load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")
load(
    "@fbsource//xplat/thrift:defs.bzl",
    "thrift_rust_unittest",
)

oncall("rust_thrift")

thrift_library(
    name = "thrift_test",
    languages = ["rust"],
    rust_deps = [
        "//thrift/lib/rust/test/adapter:adapters",
    ],
    thrift_srcs = {
        "test.thrift": [],
    },
    deps = [
        "//thrift/annotation:rust",
    ],
)

thrift_rust_unittest(
    name = "test",
    srcs = ["test.rs"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:futures",
        ":thrift_test-rust",
        ":thrift_test-rust-services",
        "//thrift/lib/rust:fbthrift",
    ],
)
