load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*Test.cpp"]),
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//eden/fs/nfs:nfsd_rpc",
        "//eden/fs/nfs/rpc:rpc",
        "//eden/fs/nfs/rpc:server",
        "//eden/fs/nfs/testharness:xdr_test_utils",
        "//eden/fs/utils:request_permit_vendor",
        "//folly/executors:manual_executor",
        "//folly/io:iobuf",
    ],
)
