load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "retry",
    srcs = glob(["src/**/*.rs"]),
    named_deps = {"slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat"},
    test_deps = ["//eden/mononoke/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:tokio",
    ],
)
