load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("source_control")

thrift_library(
    name = "qps_config",
    languages = [
        "py3-deprecated",
        "rust",
        "cpp2",
        "python",
    ],
    py3_namespace = "mononoke.qps",
    thrift_py_options = "json",
    thrift_rust_options = "serde",
    thrift_srcs = {"qps_config.thrift": None},
    deps = [
        "//thrift/annotation:rust",
    ],
)
