load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pycats",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/cats:cats",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/saplingnative/bindings/modules/pyconfigloader:pyconfigloader",
    ],
)
