load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "land_service",
    dott_files = glob(["test-land-service*.t"]),
    deps = [
        "//eden/mononoke:backfill_mapping",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/commit_rewriting/backsyncer:backsyncer_cmd",
        "//eden/mononoke/land_service/facebook/server:land_service",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
