[package]
name = "thrift_streaming_thriftclients"
version = "0.1.0"
authors = ["Facebook Source Control Team <sourcecontrol-dev@fb.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.98"
edenfs-error = { version = "0.1.0", path = "../../cli_rs/edenfs-error" }
fbinit = { version = "0.2.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "main" }
fbthrift = { version = "0.0.1+unstable", git = "https://github.com/facebook/fbthrift.git", branch = "main" }
fbthrift_socket = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "main" }
syn = { version = "1.0.109" }
thrift_streaming_clients = { version = "0.1.0", path = "../thrift_streaming/clients" }
tokio = { version = "1.45.0", features = ["full", "test-util", "tracing"] }

[lib]
path = "lib.rs"
test = false
doctest = false
doc = false
