load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "server",
    # These tests have been vetted to run well without network access. Please investigate any failure thoroughly before disabling.
    disable_all_network_access_target = True,
    dott_files =
        glob(
            [
                "*.t",
            ],
        ),
    deps = [
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        # TODO: This is required for test-getpackv2-multibyte-filenames.t, as
        # hg can't handle UTF-8 file names correctly. Once that is fixed, this
        # dep can be removed.
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/tests/integration:urlencode",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
        "//eden/mononoke:blobstore_healer",
    ],
)

dott_test(
    name = "server-mysql",
    # These tests have been vetted to run well without network access. Please investigate any failure thoroughly before disabling.
    disable_all_network_access_target = True,
    dott_files =
        [
            "test-infinitepush-mutation.t",
            "test-pushrebase.t",
            "test-server-init.t",
            "test-server-lookup.t",
        ],
    use_mysql = True,
    deps = [
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
