load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*.cpp"]),
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "fbsource//third-party/googletest:gtest",
        "//eden/common/testharness:temp_file",
        "//eden/fs/monitor:edenfs_monitor_lib",
        "//eden/fs/testharness:fake_clock",
        "//folly:range",
        "//folly/logging:logging",
    ],
)
