[package]
name = "bookmarks_validator"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
bookmarks = { path = "../../bookmarks" }
cmdlib = { path = "../../cmdlib" }
cmdlib_x_repo = { path = "../../cmdlib/x_repo" }
context = { path = "../../server/context" }
cross_repo_sync = { path = "../cross_repo_sync" }
live_commit_sync_config = { path = "../live_commit_sync_config" }
mononoke_types = { path = "../../mononoke_types" }
pushredirect_enable = { path = "../../../../configerator/structs/scm/mononoke/pushredirect" }
scuba_ext = { path = "../../common/scuba_ext" }
synced_commit_mapping = { path = "../synced_commit_mapping" }
cached_config = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
slog = { version = "2.5", features = ["max_level_debug"] }
tokio = { version = "=0.2.13", features = ["full"] }

[dev-dependencies]
cross_repo_sync_test_utils = { path = "../cross_repo_sync/test_utils" }
tests_utils = { path = "../../tests/utils" }
tokio-compat = "0.1"
