load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "observability",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/common/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:regex",
        "//common/rust/shed/cached_config:cached_config",
        "//common/rust/shed/scuba_stub:scuba",
        "//configerator/structs/scm/mononoke/observability:observability_config-rust",
        "//thrift/lib/rust:fbthrift",
    ],
)
