[package]
name = "unbundle"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "GPLv2+"

[dependencies]
anyhow = "1.0"
ascii = "1.0"
backsyncer = { version = "0.1.0", path = "../../commit_rewriting/backsyncer" }
blobrepo = { version = "0.1.0", path = "../../blobrepo" }
blobrepo_hg = { version = "0.1.0", path = "../../blobrepo/blobrepo_hg" }
blobstore = { version = "0.1.0", path = "../../blobstore" }
bookmarks = { version = "0.1.0", path = "../../bookmarks" }
bookmarks_movement = { version = "0.1.0", path = "../../bookmarks/bookmarks_movement" }
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
cacheblob = { version = "0.1.0", path = "../../blobstore/cacheblob" }
cloned = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
context = { version = "0.1.0", path = "../../server/context" }
cross_repo_sync = { version = "0.1.0", path = "../../commit_rewriting/cross_repo_sync" }
filestore = { version = "0.1.0", path = "../../filestore" }
futures = { version = "0.3.13", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.31" }
futures_ext = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
getbundle_response = { version = "0.1.0", path = "../getbundle_response" }
hex = "0.4"
hooks = { version = "0.1.0", path = "../../hooks" }
lazy_static = "1.0"
limits = { version = "0.1.0", path = "../../../../configerator/structs/scm/mononoke/loadshedding" }
live_commit_sync_config = { version = "0.1.0", path = "../../commit_rewriting/live_commit_sync_config" }
manifest = { version = "0.1.0", path = "../../manifest" }
maplit = "1.0"
mercurial_bundle_replay_data = { version = "0.1.0", path = "../../mercurial/bundle_replay_data" }
mercurial_bundles = { version = "0.1.0", path = "../../mercurial/bundles" }
mercurial_mutation = { version = "0.1.0", path = "../../mercurial/mutation" }
mercurial_revlog = { version = "0.1.0", path = "../../mercurial/revlog" }
mercurial_types = { version = "0.1.0", path = "../../mercurial/types" }
metaconfig_types = { version = "0.1.0", path = "../../metaconfig/types" }
mononoke_repo = { version = "0.1.0", path = "../mononoke_repo" }
mononoke_types = { version = "0.1.0", path = "../../mononoke_types" }
obsolete = { version = "0.1.0", path = "../obsolete" }
pin-project = "0.4"
pushrebase = { version = "0.1.0", path = "../../pushrebase" }
quickcheck = "0.9"
reachabilityindex = { version = "0.1.0", path = "../../reachabilityindex" }
remotefilelog = { version = "0.1.0", path = "../remotefilelog" }
repo_read_write_status = { version = "0.1.0", path = "../repo_read_write_status" }
reverse_filler_queue = { version = "0.1.0", path = "../reverse_filler_queue" }
scribe_commit_queue = { version = "0.1.0", path = "../scribe_commit_queue" }
scuba_ext = { version = "0.1.0", path = "../../common/scuba_ext" }
sha2 = "0.8"
slog = { version = "2.5", features = ["max_level_trace"] }
stats = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
synced_commit_mapping = { version = "0.1.0", path = "../../commit_rewriting/synced_commit_mapping" }
thiserror = "1.0"
time_window_counter = { version = "0.1.0", path = "../../time_window_counter" }
tokio = { version = "1.4", features = ["full", "test-util"] }
topo_sort = { version = "0.1.0", path = "../../common/topo_sort" }
tunables = { version = "0.1.0", path = "../../tunables" }
wirepack = { version = "0.1.0", path = "../wirepack" }

[dev-dependencies]
fbinit = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit-tokio = { version = "0.1.0", git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
itertools = "0.8"
mercurial_types-mocks = { version = "0.1.0", path = "../../mercurial/types/mocks" }
quickcheck_async = "0.1.1"
quickcheck_macros = "0.8"
test_repo_factory = { version = "0.1.0", path = "../../repo_factory/test_repo_factory" }

[patch.crates-io]
addr2line = { git = "https://github.com/gimli-rs/addr2line.git", rev = "0b6b6018b5b252a18e628fba03885f7d21844b3c" }
async-compression = { git = "https://github.com/ahornby/async-compression", rev = "c7fe7f9512e742f0c0097a19de0fca89da140b31" }
bytecount = { git = "https://github.com/llogiq/bytecount", rev = "469eaf8395c99397cd64d059737a9054aa014088" }
chashmap = { git = "https://gitlab.redox-os.org/ahornby/chashmap", rev = "901ace2ca3cdbc2095adb1af111d211e254e2aae" }
const-random = { git = "https://github.com/fbsource/const-random", rev = "374c5b46427fe2ffbf6acbd9c1687e0f1a809f95" }
curl = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
curl-sys = { git = "https://github.com/kulshrax/curl-rust", rev = "2a15bbd8dbbd54734313fa703a64db7ce6ddaff0" }
enumset = { git = "https://github.com/danobi/enumset", rev = "4c01c583c27a725948fededbfb3461c572a669a4" }
lru-disk-cache = { git = "https://github.com/mozilla/sccache", rev = "033ebaae69beeb0ac04e8c35d6ff1103487bd9a3" }
mysql_common = { git = "https://github.com/iammxt/rust_mysql_common", rev = "0e4c86952f1e799960e736c0b2bb9d2a6d935bf1" }
openssl = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
openssl-sys = { git = "https://github.com/sfackler/rust-openssl", rev = "68fc8ba890d77986b06ca5ce29d1089285fbbcf9" }
petgraph = { git = "https://github.com/jkeljo/petgraph", rev = "e3e9dd8632d23973fdc0b42c1117d5e5fc5fa384" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-build = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
r2d2_sqlite = { git = "https://github.com/jsgf/r2d2-sqlite.git", rev = "6d77a828ca0a3c507a3f58561532a1b6c66c7918" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "dotted-table-0.5.7" }
