load("//eden/scm:targets.bzl", "sl_rust_library")

oncall("sapling")

sl_rust_library(
    name = "redacted",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/blob:blob",
        "//eden/scm/lib/types:types",
    ],
)
