load("//eden/scm:targets.bzl", "sl_rust_binary")

oncall("sapling")

sl_rust_binary(
    name = "xdiff-cli",
    srcs = [
        "src/main.rs",
    ],
    crate_root = "src/main.rs",
    deps = [
        "fbsource//third-party/rust:clap",
        "//eden/scm/lib/xdiff:xdiff",
    ],
)
