load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("scm_server_infra")

thrift_library(
    name = "derivation_queue_thrift",
    languages = [
        "rust",
    ],
    thrift_srcs = {
        "derivation_queue.thrift": [],
    },
    deps = [
        "//eden/mononoke/mononoke_types/serialization:mononoke_types_serialization",
        "//thrift/annotation:rust",
        "//thrift/annotation:thrift",
    ],
)
