load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("scm_server_treehugger")

thrift_library(
    name = "bonsai_p4_mapping_thrift",
    languages = [
        "rust",
    ],
    thrift_srcs = {
        "bonsai_p4_mapping.thrift": [],
    },
    # The Thrift definitions are private and only used for serialization -- do
    # not allow other code to use them.
    visibility = [
        "//eden/mononoke/repo_attributes/bonsai_p4_mapping:",
    ],
    deps = [
        "//eden/mononoke/mononoke_types/serialization:mononoke_types_serialization",
        "//thrift/annotation:rust",
        "//thrift/annotation:thrift",
    ],
)
