load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pynodemap",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/nodemap:nodemap",
        "//eden/scm/lib/types:types",
    ],
)
