load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("sapling")

rust_binary(
    name = "vfs-benches",
    srcs = glob([
        "src/**/*.rs",
    ]),
    crate_root = "src/main.rs",
    deps = [
        "fbsource//third-party/rust:tempfile",
        "//eden/scm/lib/dev-logger:dev-logger",
        "//eden/scm/lib/minibench:minibench",
        "//eden/scm/lib/types:types",
        "//eden/scm/lib/vfs:vfs",
    ],
)
