#!/usr/bin/env python
#
# mercurial - scalable distributed SCM
#
# Copyright 2005, 2006 Matt Mackall <mpm@selenic.com>
#
# This software may be used and distributed according to the terms
# of the GNU General Public License, incorporated herein by reference.

from mercurial import commands

commands.run()
