try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

setup(
    name='fbhgext',
    version='0.1.2',
    author='Durham Goode',
    maintainer='Durham Goode',
    maintainer_email='durham@fb.com',
    url='',
    description='Facebook specific mercurial extensions',
    long_description="",
    keywords='fb hg mercurial',
    license='',
    py_modules=[
        'arcdiff',
        'automv',
        'backups',
        'bundle2hooks',
        'catnotate',
        'chistedit',
        'commitextras',
        'dirsync',
        'errorredirect',
        'extutil',
        'fastmanifest',
        'fbamend',
        'fbconduit',
        'fbhistedit',
        'githelp',
        'gitlookup',
        'gitrevset',
        'inhibitwarn',
        'logtoprocess',
        'manifestdiskcache',
        'mergedriver',
        'morestatus',
        'perftweaks',
        'phabdiff',
        'phrevset',
        'phabstatus',
        'pullcreatemarkers',
        'pushrebase',
        'pushvars',
        'rage',
        'reflog',
        'reset',
        'show',
        'simplecache',
        'smartlog',
        'sparse',
        'statprof',
        'suppresscommandfailure',
        'tweakdefaults',
        'upgradegeneraldelta',
    ],
    packages=[
        'copytrace',
    ]
)
