load("//dsi/logger/thriftcodegen:logger_config.bzl", "logger_config")

oncall("scm_server_infra")

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeAppStatsLoggerConfig",
    src_file = "MononokeAppStats.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeSaplingApiRequestLoggerConfig",
    src_file = "MononokeSaplingApiRequest.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeGitRequestLoggerConfig",
    src_file = "MononokeGitRequest.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeWarmBookmarkCacheStatsLoggerConfig",
    src_file = "MononokeWarmBookmarkCacheStats.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeApiStatsLoggerConfig",
    src_file = "MononokeApiStats.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeScsRequestLoggerConfig",
    src_file = "MononokeScsRequest.thrift",
)

logger_config(
    is_ods3_enabled = True,
    languages = ["rust"],
    logger_name = "MononokeRepoFactoryStatsLoggerConfig",
    src_file = "MononokeRepoFactoryStats.thrift",
)
