load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "git_locator",
    srcs = glob([
        "src/**/*.rs",
    ]),
    named_deps = {"slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat"},
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-retry",
        "//common/rust/shed/borrowed:borrowed",
        "//common/rust/shed/cloned:cloned",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/smc:smc",
        "//common/rust/smc-updates:smc-updates",
        "//common/rust/thrift/srclient:srclient",
        "//eden/mononoke/cmdlib/sharding_ext:sharding_ext",
        "//eden/mononoke/common/scuba_ext:scuba_ext",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
)
