// @generated SignedSource<<395c2b4611721c4507239d7610a9d912>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/megarepo/all_config_versions.thrift

include "configerator/structs/scm/mononoke/megarepo/megarepo_configs.thrift"

namespace cpp2 facebook.scm.service
namespace py3 scm.service.thrift
namespace py scm.service.thrift.all_config_versions

/// Relative path of a .cconf file, which has an expected config value
typedef string CconfPath

/// Versions of all the SyncTargetConfigs for a given Target
struct TargetConfigVersions {
    /// Target
    1: megarepo_configs.Target target,
    /// A version -> cconf path mapping for easy file lookup
    2: map<megarepo_configs.SyncConfigVersion, CconfPath> config_paths,
}

/// All megarepo targets
struct MegarepoTargets {
    /// All megarepo targets
    1: list<TargetConfigVersions> targets,
}



