.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CHG 1 "March 3, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
chg \- a fast client for Mercurial command server
.SH SYNOPSIS
.B chg
.IR command " [" options "] [" arguments "]..."
.br
.SH DESCRIPTION
The
.B chg
command is the wrapper for
.B hg
command.
It uses the Mercurial command server to reduce start-up overhead.
.SH OPTIONS
This program accepts the same command line syntax as the
.B hg
command. Additionally it accepts the following options.
.TP
.B \-\-kill\-chg\-daemon
Terminate the background command servers.
.SH SEE ALSO
.BR hg (1),
.SH AUTHOR
Written by Yuya Nishihara <yuya@tcha.org>.
