load("//eden/scm:targets.bzl", "sl_rust_library")

oncall("source_control")

sl_rust_library(
    name = "cxxerror",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
    ],
)
