load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pymodules",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:tracing",
        "//eden/scm/lib/minibytes:minibytes",
        "//eden/scm/lib/python-modules:python-modules",
        "//eden/scm/saplingnative/bindings/modules/pybytes:pybytes",
    ],
)
