load("@fbcode_macros//build_defs/lib:rust_oss.bzl", "rust_oss")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "hook_manager",
    srcs = glob([
        "src/**/*.rs",
    ]),
    autocargo = {
        "cargo_target_config": {
            "doctest": False,
            "test": False,
        },
    },
    test_deps = [
        "fbsource//third-party/rust:maplit",
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//common/rust/shed/sorted_vector_map:sorted_vector_map",
        "//eden/mononoke/common/metadata:metadata",
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
        "//eden/mononoke/mononoke_types:mononoke_types-mocks",
        "//eden/mononoke/repo_attributes/hook_manager/hook_manager_testlib:hook_manager_testlib",
        "//eden/mononoke/repo_factory:test_repo_factory",
        "//eden/mononoke/tests/utils:tests_utils",
    ]
    + (
        # The employee-service mock used by the bypass author-resolution test is
        # fbcode-only; the test using it is gated on #[cfg(fbcode_build)].
        []
        if rust_oss.is_oss_build()
        else [
            "//eden/mononoke/facebook/employee_service:employee_service",
        ]
    ),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tracing",
        "//common/rust/shed/cloned:cloned",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/futures_stats:futures_stats",
        "//common/rust/shed/scuba_stub:scuba",
        "//eden/mononoke/blobstore:blobstore",
        "//eden/mononoke/common/permission_checker:permission_checker",
        "//eden/mononoke/common/rust/justknobs_ext:justknobs",
        "//eden/mononoke/common/scuba_ext:scuba_ext",
        "//eden/mononoke/derived_data:changeset_info",
        "//eden/mononoke/derived_data:fsnodes",
        "//eden/mononoke/derived_data:skeleton_manifest",
        "//eden/mononoke/derived_data:unodes",
        "//eden/mononoke/derived_data/content_manifest_derivation:content_manifest_derivation",
        "//eden/mononoke/manifest:manifest",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/bonsai_git_mapping:bonsai_git_mapping",
        "//eden/mononoke/repo_attributes/bonsai_tag_mapping:bonsai_tag_mapping",
        "//eden/mononoke/repo_attributes/bookmarks:bookmarks",
        "//eden/mononoke/repo_attributes/bookmarks/bookmarks_types:bookmarks_types",
        "//eden/mononoke/repo_attributes/commit_graph/commit_graph:commit_graph",
        "//eden/mononoke/repo_attributes/commit_rate_limit:commit_rate_limit_config",
        "//eden/mononoke/repo_attributes/filestore:filestore",
        "//eden/mononoke/repo_attributes/repo_blobstore:repo_blobstore",
        "//eden/mononoke/repo_attributes/repo_cross_repo:repo_cross_repo",
        "//eden/mononoke/repo_attributes/repo_derivation_queues/if:derivation_queue_thrift-rust",
        "//eden/mononoke/repo_attributes/repo_derived_data:repo_derived_data",
        "//eden/mononoke/repo_attributes/repo_identity:repo_identity",
        "//eden/mononoke/repo_attributes/repo_permission_checker:repo_permission_checker",
        "//eden/mononoke/repo_attributes/restricted_paths:restricted_paths",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
    ]
    + (
        # Only used under #[cfg(fbcode_build)] to resolve a commit author's
        # canonical unixname for the hook-bypass permission re-check, so keep it
        # out of the OSS build/Cargo.toml.
        []
        if rust_oss.is_oss_build()
        else [
            "//eden/mononoke/facebook/employee_service:employee_service",
        ]
    ),
)
