[package]
name = "synced_commit_mapping"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["schemas/**/*.sql", "src/**/*.rs", "test/**/*.rs"]

[lib]
path = "src/lib.rs"

[[test]]
name = "synced_commit_mapping_test"
path = "test/main.rs"

[dependencies]
context = { path = "../../server/context" }
mononoke_types = { path = "../../mononoke_types" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures-old = { package = "futures", version = "0.1" }
thiserror = "1.0"

[dev-dependencies]
mononoke_types-mocks = { path = "../../mononoke_types/mocks" }
async_unit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
futures = { version = "0.3", features = ["async-await", "compat"] }
