#!/bin/sh
#

hg init t
cd t
echo 1 > foo
hg ci -Am m

cd ..
hg clone t tt
cd tt
echo 1.1 > foo
hg ci -Am m

cd ../t
echo 1.2 > foo
hg ci -Am m
echo % should fail
hg pull -u ../tt

cd ../tt
echo % should fail
hg pull -u ../t
HGMERGE=true hg merge
hg ci -mm

cd ../t
echo % should work
hg pull -u ../tt
