#!/bin/sh

"$TESTDIR/hghave" inotify || exit 80

hg init

touch a b c d e
mkdir dir
mkdir dir/bar
touch dir/x dir/y dir/bar/foo

hg ci -Am m

echo "[extensions]" >> $HGRCPATH
echo "inotify=" >> $HGRCPATH

echo % inserve
hg inserve -d --pid-file=hg.pid
cat hg.pid >> "$DAEMON_PIDS"

# let the daemon finish its stuff
sleep 1
# issue907
hg status
echo % clean
hg status -c
echo % all
hg status -A

kill `cat hg.pid`
