#!/bin/sh

hg init
touch a
hg add a
hg commit -m "Added a"

touch main
hg add main
hg commit -m "Added main"
hg checkout 0

echo Main should be gone
ls

touch side1
hg add side1
hg commit -m "Added side1"
touch side2
hg add side2
hg commit -m "Added side2"

hg log

echo Should have two heads, side2 and main
hg heads

echo Should show "a side1 side2"
ls

hg update --debug -C 1
echo Should only show "a main"
ls

