#!/bin/sh

echo '% hg init t'
hg init t
cd t
echo foo > a
echo '% hg add a'
hg add a
echo '% hg commit'
hg commit -m "1" -d "1000000 0"
echo '% hg verify'
hg verify
chmod -r .hg/store/data/a.i
echo '% hg verify'
hg verify 2>/dev/null || echo verify failed
chmod +r .hg/store/data/a.i
echo '% hg verify'
hg verify 2>/dev/null || echo verify failed
chmod -w .hg/store/data/a.i
echo barber > a
echo '% hg commit'
hg commit -m "2" -d "1000000 0" 2>/dev/null || echo commit failed
chmod -w .
echo '% hg diff'
hg diff --nodates
chmod +w .

chmod +w .hg/store/data/a.i
mkdir dir
touch dir/a
echo '% hg status'
hg status
chmod -rx dir
echo '% hg status'
hg status
# reenable perm to allow deletion
chmod +rx dir
