#!/bin/sh

"$TESTDIR/hghave" inotify || exit 80

hg init

echo "[extensions]" >> $HGRCPATH
echo "inotify=" >> $HGRCPATH

echo % inserve
hg inserve -d --pid-file=hg.pid
cat hg.pid >> "$DAEMON_PIDS"

# let the daemon finish its stuff
sleep 1

echo % empty
hg debuginotify

mkdir a
sleep 1

echo % only 'a'
hg debuginotify

rmdir a
sleep 1

echo % empty again
hg debuginotify

kill `cat hg.pid`
