#!/bin/sh

hg init
echo foo > a
hg add a
hg commit -m "1"

echo bar > b
hg add b
hg remove a

echo "%%% should show a removed and b added"
hg status

echo "reverting..."
hg revert --all

echo "%%% should show b unknown and a back to normal"
hg status

rm b

hg co -C 0
echo foo-a > a
hg commit -m "2a"

hg co -C 0
echo foo-b > a
hg commit -m "2b"

HGMERGE=true hg merge 1

echo "%%% should show foo-b"
cat a

echo bar > b
hg add b
rm a
hg remove a

echo "%%% should show a removed and b added"
hg status

echo "%%% revert should fail"
hg revert --all

echo "%%% revert should be ok now"
hg revert -r2 --all

echo "%%% should show b unknown and a marked modified (merged)"
hg status

echo "%%% should show foo-b"
cat a

