#!/bin/sh

# test mq hardlinking
echo "[extensions]" >> $HGRCPATH
echo "mq=" >> $HGRCPATH

echo % init
hg init a
cd a

hg qimport -n foo - << EOF
diff -r 2588a8b53d66 a
--- /dev/null	Thu Jan 01 00:00:00 1970 +0000
+++ b/a	Wed Jul 23 15:54:29 2008 +0200
@@ -0,0 +1,1 @@
+a
EOF

hg qpush

cd ..
cp -al a b
cd b

hg qimport -n bar - << EOF
diff -r 2588a8b53d66 a
--- /dev/null	Thu Jan 01 00:00:00 1970 +0000
+++ b/b	Wed Jul 23 15:54:29 2008 +0200
@@ -0,0 +1,1 @@
+b
EOF

hg qpush

cat .hg/patches/status
echo %
cat .hg/patches/series
echo %%%
cat ../a/.hg/patches/status
echo %
cat ../a/.hg/patches/series

# test tags hardlinking
hg qdel -r qbase:qtip

hg tag -l lfoo
hg tag foo

cd ..
cp -al b c
cd c

hg tag -l -r 0 lbar
hg tag -r 0 bar
echo %%%
cat .hgtags
echo %
cat .hg/localtags
echo %%%
cat ../b/.hgtags
echo %
cat ../b/.hg/localtags
