#!/bin/sh

hg init repo
cd repo

echo a > a
hg ci -qAm 'add a'

echo b > b
hg ci -qAm 'add b'

hg up -qC 0
hg rm a
hg ci -m 'rm a'

hg up -qC 1
rm a

echo '% local deleted a file, remote removed'
hg -v merge
echo % should show a as removed
hg st

hg ci -m merge
echo % manifest. should not have a:
hg manifest
