#!/bin/sh

hg init repo
cd repo
echo foo > foo
hg ci -qAm 'add foo'
echo >> foo
hg ci -m 'change foo'
hg up -qC 0
echo bar > bar
hg ci -qAm 'add bar'
hg log
cd ..
hg init copy
cd copy

echo '% pull a missing revision'
hg pull -qr missing ../repo

echo '% pull multiple revisions with update'
hg pull -qu -r 0 -r 1 ../repo
hg -q parents
hg rollback

echo '% pull -r 0'
hg pull -qr 0 ../repo
hg log

echo '% pull -r 1'
hg pull -qr 1 ../repo
hg log

# this used to abort: received changelog group is empty
echo '% pull -r 1 again'
hg pull -qr 1 ../repo
