#!/bin/sh
#

hg init foo
cd foo
touch a


unset HGUSER
echo "[ui]" >> .hg/hgrc
echo "username= foo" >> .hg/hgrc
echo "          bar1" >> .hg/hgrc

hg ci -Am m

rm .hg/hgrc

HGUSER=`(echo foo; echo bar2)` hg ci -Am m

hg ci -Am m -u "`(echo foo; echo bar3)`"

true
