#!/bin/sh

"$TESTDIR/hghave" svn svn-bindings || exit 80

echo "[extensions]" >> $HGRCPATH
echo "convert = " >> $HGRCPATH
echo "graphlog =" >> $HGRCPATH

svnadmin create svn-repo
cat "$TESTDIR/svn/tags.svndump" | svnadmin load svn-repo > /dev/null

echo % convert
hg convert --datesort svn-repo A-hg

cd A-hg
hg glog --template '{rev} {desc|firstline} tags: {tags}\n'
hg tags | sed 's/:.*/:/'
cd ..

echo % convert without tags
hg convert --datesort --config convert.svn.tags= svn-repo A-notags-hg
hg -R A-notags-hg tags -q

