#!/bin/sh

mkdir t
cd t
hg init
echo "[merge]" >> .hg/hgrc
echo "followcopies = 1" >> .hg/hgrc
echo foo > a
echo foo > a2
hg add a a2
hg ci -m "start"
hg mv a b
hg mv a2 b2
hg ci -m "rename"
echo "checkout"
hg co 0
echo blahblah > a
echo blahblah > a2
hg mv a2 c2
hg ci -m "modify"
echo "merge"
hg merge -y --debug
hg status -AC
cat b
hg ci -m "merge"
hg debugindex .hg/store/data/b.i
hg debugrename b
