#!/bin/sh

cat >> $HGRCPATH <<EOF
[extensions]
hgcia=

[hooks]
changegroup.cia = python:hgext.hgcia.hook

[cia]
user = testuser
project = testproject
test = True
EOF

hg init src
hg init cia

cd src
echo foo > foo
hg ci -Amfoo

hg push ../cia
