#!/bin/sh

hg init t
cd t
echo foo > a
hg add a
hg commit -m "1" -d "1000000 0"
hg verify
chmod -r .hg/store/data/a.i
hg verify 2>/dev/null || echo verify failed
chmod +r .hg/store/data/a.i
hg verify 2>/dev/null || echo verify failed
chmod -w .hg/store/data/a.i
echo barber > a
hg commit -m "2" -d "1000000 0" 2>/dev/null || echo commit failed
chmod -w .
hg diff --nodates
chmod +w .

chmod +w .hg/store/data/a.i
mkdir dir
touch dir/a
hg status
chmod -rx dir
hg status
# reenable perm to allow deletion
chmod +rx dir
