#!/bin/sh

hglocate()
{
    echo "hg locate $@"
    hg locate "$@"
    ret=$?
    echo
    return $ret
}

mkdir t
cd t
hg init
echo 0 > a
echo 0 > b
echo 0 > t.h
mkdir t
echo 0 > t/x
hg ci -A -m m -d "1000000 0"
touch nottracked
hglocate a && echo locate succeeded || echo locate failed
hglocate NONEXISTENT && echo locate succeeded || echo locate failed
hglocate
hg rm a
hg ci -m m -d "1000000 0"
hglocate a
hglocate NONEXISTENT
hglocate
hglocate -r 0 a
hglocate -r 0 NONEXISTENT
hglocate -r 0
echo % -I/-X with relative path should work
cd t
hglocate
hglocate -I ../t
# test issue294
cd ..
rm -r t
hglocate t
