#!/bin/sh

echo % setting up repo
hg init test
cd test
echo a > a
hg ci -Ama
hg rm a
hg ci -mdel

echo % set up hgweb
hg serve -n test -p $HGPORT -d --pid-file=hg.pid -A access.log -E errors.log
cat hg.pid >> $DAEMON_PIDS

echo % revision
"$TESTDIR/get-with-headers.py" localhost:$HGPORT '/rev/tip'

echo % diff removed file
"$TESTDIR/get-with-headers.py" localhost:$HGPORT '/diff/tip/a'
