#!/bin/sh

hg init repo
cd repo

touch foo
hg ci -Am 'add foo'

hg up -C null
# this should be stored as a delta against rev 0
echo foo bar baz > foo
hg ci -Am 'add foo again'

hg debugindex .hg/store/data/foo.i
