#!/bin/sh

mkdir t
cd t
hg init
echo a > a
hg ci -Ama
echo b > b
hg branch b
hg ci -Amb
hg co -C 0

echo fast-forward
hg merge b
hg ci -Ammerge

echo bogus fast-forward should fail
hg merge b

echo done
