#!/bin/sh

hg init rep
cd rep
mkdir dir
touch foo dir/bar
hg -v addremove
hg -v commit -m "add 1" -d "1000000 0"
cd dir/
touch ../foo_2 bar_2
hg -v addremove
hg -v commit -m "add 2" -d "1000000 0"

cd ..
hg init sim
cd sim
echo a > a
echo a >> a
echo a >> a
echo c > c
hg commit -Ama
mv a b
rm c
echo d > d
hg addremove -n -s 50 # issue 1696
hg addremove -s 50
hg commit -mb
