#!/bin/sh

# Source bundle was generated with the following script.
#
# hg init
# echo a > a
# ln -s a l
# hg ci -Ama -d'0 0'
# mkdir b
# echo a > b/a
# chmod +x b/a
# hg ci -Amb -d'1 0'

hg init
hg -q pull "$TESTDIR/test-manifest.hg"

hg manifest
hg manifest -v
hg manifest --debug
hg manifest -r 0
hg manifest -r 1
hg manifest -r tip

echo % should fail
hg manifest -r 2
hg manifest -r tip tip

hg manifest tip
