#!/bin/sh

cat > $HGRCPATH <<EOF
[diff]
git = True

[extensions]
eol =

[eol]
native = CRLF
EOF

echo "% setup repository"
hg init repo
cd repo

cat > .hgeol <<EOF
[patterns]
**.txt = native
EOF

printf "first\r\nsecond\r\nthird\r\n" > a.txt
hg commit --addremove -m 'checkin'
cd ..

echo "% hg clone repo repo-2"
hg clone repo repo-2
cd repo-2

echo '% printrepr.py a.txt'
python $TESTDIR/printrepr.py < a.txt
echo '% hg cat a.txt'
hg cat a.txt | python $TESTDIR/printrepr.py

hg remove .hgeol
hg commit -m 'remove eol'
hg push --quiet

cd ..

# Test clone of repo with .hgeol in working dir, but no .hgeol in tip
echo "% hg clone repo repo-3"
hg clone repo repo-3
cd repo-3

echo '% printrepr.py a.txt'
python $TESTDIR/printrepr.py < a.txt

cd ..

# Test clone of revision with .hgeol
echo "% hg clone -r 1 repo repo-4"
hg clone -r 0 repo repo-4
cd repo-4

echo '% cat .hgeol'
cat .hgeol

echo '% printrepr.py a.txt'
python $TESTDIR/printrepr.py < a.txt

cd ..
