#!/bin/sh

source $TESTDIR/helpers.sh
echo "[extensions]" >> $HGRCPATH
echo "bookmarks=" >> $HGRCPATH
echo "mq=" >> $HGRCPATH

hg init

echo qqq>qqq.txt

echo % add file
hg add

echo % commit first revision
hg ci -m 1 -u user -d "1 0"

echo % set bookmark
hg book test

echo www>>qqq.txt

echo % commit second revision
hg ci -m 2 -u usr -d "1 0"

echo % set bookmark
hg book test2

echo % update to -2
hg update -r -2

echo eee>>qqq.txt

echo % commit new head
hg ci -m 3 -u user -d "1 0"

echo % bookmarks updated?
hg book

echo % strip to revision 1
hg strip 1 | hidebackup

echo % list bookmarks
hg book

