#!/bin/sh

hg init

echo a > a
hg ci -d '0 0' -Ama

hg an a

HGRCPATH=$HGTMP/.hgrc; export HGRCPATH
echo "[ui]" >> $HGTMP/.hgrc
echo "strict=True" >> $HGTMP/.hgrc

hg an a
hg annotate a

echo % should succeed - up is an alias, not an abbreviation

hg up
