#!/bin/sh

"$TESTDIR/hghave" execbit || exit 80

hg init repo
cd repo
echo foo > foo
chmod 644 foo
hg ci -qAm '644'

chmod 755 foo
hg ci -qAm '755'

echo '% reverting to rev 0'
hg revert -a -r 0
hg st
hg diff --git
