#!/bin/sh

hg init
echo a > a
hg ci -Am0
hg -q clone . foo

touch .hg/store/journal

echo foo > a
hg ci -Am0

hg recover

echo % check that zero-size journals are correctly aborted
hg bundle -qa repo.hg
chmod -w foo/.hg/store/00changelog.i
hg -R foo unbundle repo.hg 2>&1 | sed 's/\(abort: Permission denied\).*/\1/'
if test -f foo/.hg/store/journal; then echo 'journal exists :-('; fi
exit 0
