#!/bin/sh

"$TESTDIR/hghave" inotify || exit 80

hg init

touch a
mkdir dir
touch dir/b
touch dir/c

echo "[extensions]" >> $HGRCPATH
echo "inotify=" >> $HGRCPATH

hg add dir/c

echo % inserve
hg inserve -d --pid-file=hg.pid 2>&1
cat hg.pid >> "$DAEMON_PIDS"

hg st

echo % moving dir out
mv dir ../tmp-test-inotify-issue1542

echo % status
hg st

sleep 1
echo "Are we able to kill the service? if not, the service died on some error"
kill `cat hg.pid`

