#!/bin/sh

"$TESTDIR/hghave" inotify || exit 80

hg init

touch a b
hg add a b
rm b

echo % status without inotify
hg st

echo "[extensions]" >> $HGRCPATH
echo "inotify=" >> $HGRCPATH

echo % inserve
hg inserve -d --pid-file=hg.pid 2>&1
cat hg.pid >> "$DAEMON_PIDS"

echo % status
hg st

sleep 1
echo "Are we able to kill the service? if not, the service died on some error"
kill `cat hg.pid`

