#!/bin/sh

"$TESTDIR/hghave" inotify || exit 80

echo "[extensions]" >> $HGRCPATH
echo "inotify=" >> $HGRCPATH

p="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
hg init $p
cd $p

echo % fail
ln -sf doesnotexist .hg/inotify.sock
hg st
hg inserve
rm .hg/inotify.sock

echo % inserve
hg inserve -d --pid-file=hg.pid
cat hg.pid >> "$DAEMON_PIDS"
echo % status
hg status

kill `cat hg.pid`
