#!/bin/sh

. $TESTDIR/helpers.sh

echo "[extensions]" >> $HGRCPATH
echo "rebase=" >> $HGRCPATH
echo "bookmarks=" >> $HGRCPATH

echo % initialize repository
hg init

echo 'a' > a
hg ci -A -m "0"

echo 'b' > b
hg ci -A -m "1"

hg up 0
echo 'c' > c
hg ci -A -m "2"

echo 'd' > d
hg ci -A -m "3"

hg bookmark -r 1 one
hg bookmark -r 3 two

echo % bookmark list
hg bookmark

echo % rebase
hg rebase -s two -d one 2>&1 | cleanrebase

hg log
