#!/bin/sh

"$TESTDIR/hghave" docutils || exit 80

HGENCODING=UTF-8
export HGENCODING

for PO in C $TESTDIR/../i18n/*.po; do
    LOCALE=`basename $PO .po`
    echo
    echo "% extracting documentation from $LOCALE"
    echo ".. -*- coding: utf-8 -*-" > gendoc-$LOCALE.txt
    echo "" >> gendoc-$LOCALE.txt
    LC_ALL=$LOCALE python $TESTDIR/../doc/gendoc.py >> gendoc-$LOCALE.txt 2> /dev/null || exit

    # We call runrst without adding "--halt warning" to make it report
    # all errors instead of stopping on the first one.
    echo "checking for parse errors"
    python $TESTDIR/../doc/runrst html gendoc-$LOCALE.txt /dev/null
done
