#!/bin/sh

"$TESTDIR/hghave" symlink || exit 80

hg init a
cd a

echo '% directory moved and symlinked'
mkdir foo
touch foo/a
hg ci -Ama
mv foo bar
ln -s bar foo
echo '% now addremove should remove old files'
hg addremove
