#!/bin/sh

mkdir t
cd t
hg init

echo 1 > a
hg ci -qAm "first" -d "1000000 0"

hg cp a b
hg mv a c
echo 2 >> b
echo 2 >> c

hg ci -qAm "second" -d "1000000 0"

hg co -C 0

echo 0 > a
echo 1 >> a

hg ci -qAm "other" -d "1000000 0"

hg merge --debug

echo "-- b --"
cat b

echo "-- c --"
cat c
