#!/bin/sh

echo "[extensions]" >> $HGRCPATH
echo "patchbomb=" >> $HGRCPATH

hg init
echo a > a
hg commit -Ama -d '1 0'

hg email -n -f quux -t foo -c bar tip | \
  sed -e 's/\(Message-Id:\).*@.*/\1/' | \
  sed -e 's/\(Date:\).*/\1/'

echo b > b
hg commit -Amb -d '2 0'

# Pipe something to make raw_input() happy even under pysh+win32
echo test | hg email -n -f quux -t foo -c bar -s test 0:tip | \
  sed -e 's/\(Message-Id:\).*@.*/\1/' | \
  sed -e 's/\(In-Reply-To:\).*@.*/\1/' | \
  sed -e 's/\(Date:\).*/\1/'