#!/bin/sh
#
mkdir t
cd t
hg init
echo 0 > a
echo 0 > b
hg ci -A -m m -d "1000000 0"
hg rm a
hg cat a
hg cat --decode a # more tests in test-encode
echo 1 > b
hg ci -m m -d "1000000 0"
echo 2 > b
hg cat -r 0 a
hg cat -r 0 b
hg cat -r 1 a
hg cat -r 1 b
