#!/bin/sh

"$TESTDIR/hghave" svn svn-bindings || exit 80

echo "[extensions]" >> $HGRCPATH
echo "convert = " >> $HGRCPATH
echo "graphlog =" >> $HGRCPATH

svnadmin create svn-repo
cat "$TESTDIR/svn/startrev.svndump" | svnadmin load svn-repo > /dev/null

convert()
{
    startrev=$1
    repopath=A-r$startrev-hg
    hg convert --config convert.svn.startrev=$startrev \
        --config convert.svn.trunk=branches/branch1 \
        --config convert.svn.branches="  " \
        --config convert.svn.tags= \
        --datesort svn-repo $repopath
    hg -R $repopath glog --template '{rev} {desc|firstline} files: {files}\n'
    echo
}

echo % convert before branching point
convert 3
echo % convert before branching point
convert 4
echo % convert at branching point
convert 5
echo % convert last revision only
convert 6
