#!/bin/sh

echo "[extensions]" >> $HGRCPATH
echo "bookmarks=" >> $HGRCPATH

echo "[bookmarks]" >> $HGRCPATH
echo "track.current = True" >> $HGRCPATH

hg init

echo % no bookmarks
hg bookmarks

echo % set bookmark X
hg bookmark X

echo % list bookmarks
hg bookmark

echo % list bookmarks with color
hg --config extensions.color= --config color.mode=ansi \
    bookmark --color=always

echo % update to bookmark X
hg update X

echo % list bookmarks
hg bookmarks

echo % rename
hg bookmark -m X Z

echo % list bookmarks
hg bookmarks

echo % new bookmark Y
hg bookmark Y

echo % list bookmarks
hg bookmark

echo % commit
echo 'b' > b
hg add b
hg commit -m'test'

echo % list bookmarks
hg bookmark

echo % delete bookmarks
hg bookmark -d Y
hg bookmark -d Z

echo % list bookmarks
hg bookmark

echo % update to tip
hg update tip

