#!/bin/sh
# Some tests for hgweb in an empty repository

hg init test
cd test
hg serve -n test -p $HGPORT -d --pid-file=hg.pid -A access.log -E errors.log
cat hg.pid >> $DAEMON_PIDS

("$TESTDIR/get-with-headers.py" localhost:$HGPORT '/shortlog')
("$TESTDIR/get-with-headers.py" localhost:$HGPORT '/log')
("$TESTDIR/get-with-headers.py" localhost:$HGPORT '/graph')
("$TESTDIR/get-with-headers.py" localhost:$HGPORT '/file')
