#!/bin/sh -x

cat <<'EOF' > merge
#!/bin/sh
echo merging for `basename $1`
EOF
chmod +x merge
export HGMERGE=./merge

mkdir A1
cd A1
hg init
echo This is file foo1 > foo
echo This is file bar1 > bar
hg add foo bar
hg commit -t "commit text" -d "0 0" -u user

cd ..
hg clone A1 B1

cd A1
rm bar
hg remove bar
hg commit -t "commit test" -d "0 0" -u user

cd ../B1
echo This is file foo22 > foo
hg commit -t "commit test" -d "0 0" -u user

cd ..
hg clone A1 A2
hg clone B1 B2

cd A1
hg pull ../B1
hg update -m
hg commit -t "commit test" -d "0 0" -u user
echo bar should remain deleted.
hg manifest

cd ../B2
hg pull ../A2
hg update -m
hg commit -t "commit test" -d "0 0" -u user
echo bar should remain deleted.
hg manifest
