#!/bin/sh

hg init test
cd test

echo '[web]' > .hg/hgrc
echo 'accesslog = access.log' >> .hg/hgrc

echo % Without -v
hg serve -a localhost -p 20063 -d --pid-file=hg.pid
cat hg.pid >> "$DAEMON_PIDS"
if [ -f access.log ]; then
    echo 'access log created - .hg/hgrc respected'
fi

echo % With -v
hg serve -a localhost -p 20064 -d --pid-file=hg.pid -v
cat hg.pid >> "$DAEMON_PIDS"
