#!/bin/sh

cat >> $HGRCPATH <<EOF
[alias]
myinit = init
cleanstatus = status -c
unknown = bargle
ambiguous = s
recursive = recursive
nodefinition =
mylog = log
lognull = log -r null
shortlog = log --template '{rev} {node|short} | {date|isodate}\n'
dln = lognull --debug
nousage = rollback

[defaults]
mylog = -q
lognull = -q
log = -v
EOF

echo '% basic'
hg myinit alias

echo '% unknown'
hg unknown

echo '% ambiguous'
hg ambiguous

echo '% recursive'
hg recursive

echo '% no definition'
hg nodef

cd alias

echo '% no usage'
hg nousage

echo foo > foo
hg ci -Amfoo

echo '% with opts'
hg cleanst

echo '% with opts and whitespace'
hg shortlog

echo '% interaction with defaults'
hg mylog
hg lognull

echo '% properly recursive'
hg dln
