#!/bin/sh

"$TESTDIR/hghave" execbit || exit 80

hg init
echo a > a
hg ci -Am'not executable'

chmod +x a
hg ci -m'executable'
hg id

echo '% make sure we notice the change of mode if the cached size == -1'
hg rm a
hg revert -r 0 a
hg debugstate
hg st

hg up 0
hg id
test -x a && echo executable -- eek || echo not executable -- whew
