#!/bin/bash

mkdir test
cd test
echo foo>foo
hg init
hg addremove
hg commit -t "1"
hg verify
hg serve -p 20059 2>/dev/null &
cd ..

mkdir copy
cd copy
hg init http://localhost:20059/
hg verify
hg co
cat foo
hg manifest

kill %hg
