#!/bin/sh
# basic test for hg debugrebuildstate

hg init repo
cd repo

touch foo bar
hg ci -Am 'add foo bar'

touch baz
hg add baz
hg rm bar

echo '% state dump'
hg debugstate --nodates | sort
echo '% status'
hg st -A

hg debugrebuildstate
echo '% state dump'
hg debugstate --nodates | sort
echo '% status'
hg st -A

