#! /bin/sh

echo "[extensions]" >> $HGRCPATH
echo "mq=" >> $HGRCPATH

mkdir webdir
cd webdir

hg init a
hg --cwd a qinit -c
echo a > a/a
hg --cwd a ci -A -m a
echo b > a/b
hg --cwd a addremove
hg --cwd a qnew -f b.patch
hg --cwd a qcommit -m b.patch

hg --cwd a log --template "{desc}\n"
hg --cwd a/.hg/patches log --template "{desc}\n"

root=`pwd`

cd ..

cat > collections.conf <<EOF
[collections]
$root=$root
EOF

hg serve -p $HGPORT -d --pid-file=hg.pid --webdir-conf collections.conf \
    -A access-paths.log -E error-paths-1.log
cat hg.pid >> $DAEMON_PIDS

"$TESTDIR/get-with-headers.py" localhost:$HGPORT '/?style=raw'

hg qclone http://localhost:$HGPORT/a b
hg --cwd b log --template "{desc}\n"
hg --cwd b qpush -a
hg --cwd b log --template "{desc}\n"
