#!/bin/sh

mkdir test
cd test
echo foo>foo
hg init
hg addremove
hg commit -m 1
hg verify
hg serve -p $HGPORT -d --pid-file=hg.pid
cat hg.pid >> $DAEMON_PIDS
cd ..

hg clone --pull http://localhost:$HGPORT/ copy | sed -e "s,:$HGPORT/,:\$HGPORT/,"
cd copy
hg verify
hg co
cat foo
hg manifest --debug
hg pull | sed -e "s,:$HGPORT/,:\$HGPORT/,"

echo % issue 622
cd ..
hg init empty
cd empty
hg pull -u ../test

echo % test file: uri handling
hg pull -q file://../test-doesnt-exist 2>&1 \
    | sed 's%abort: repository.*/test-doesnt-exist%abort: repository /test-doesnt-exist%'
hg pull -q file:../test
# It's tricky to make file:// URLs working on every platforms
# with regular shell commands.
URL=`python -c "import os; print 'file://foobar' + ('/' + os.getcwd().replace(os.sep, '/')).replace('//', '/') + '/../test'"`
hg pull -q $URL
