#!/bin/sh -e

umask 027
mkdir test1
cd test1

hg init
touch a b
hg add a b
hg ci -m "added a b" -d "1000000 0"

cd ..
hg clone test1 test3
mkdir test2
cd test2

hg init
hg pull ../test1
hg co
chmod +x a
hg ci -m "chmod +x a" -d "1000000 0"
echo % the changelog should mention file a:
hg tip --template '{files}\n'

cd ../test1
echo 123 >>a
hg ci -m "a updated" -d "1000000 0"

hg pull ../test2
hg heads
hg history

hg -v merge

cd ../test3
echo 123 >>b
hg ci -m "b updated" -d "1000000 0"

hg pull ../test2
hg heads
hg history

hg -v merge

ls -l ../test[123]/a > foo
cut -b 1-10 < foo

hg debugindex .hg/store/data/a.i
hg debugindex ../test2/.hg/store/data/a.i
hg debugindex ../test1/.hg/store/data/a.i
