#!/bin/sh

echo "[extensions]" >> $HGRCPATH
echo "mq=" >> $HGRCPATH

hg init a
cd a

echo 'base' > base
hg ci -Ambase -d '1 0'

hg qnew -mmqbase mqbase
hg qrename mqbase renamed
mkdir .hg/patches/foo
hg qrename renamed foo
hg qseries
ls .hg/patches/foo
mkdir .hg/patches/bar
hg qrename foo/renamed bar
hg qseries
ls .hg/patches/bar
hg qrename bar/renamed baz
hg qseries
ls .hg/patches/baz
hg qrename baz new/dir
hg qseries
ls .hg/patches/new/dir
cd ..

echo % test patch being renamed before committed
hg init b
cd b
hg qinit -c
hg qnew x
hg qrename y
hg qcommit -m rename
cd ..


