#!/bin/sh

rm -rf a
hg init a
cd a

echo foo > foo
hg ci -qAm0
chmod +x foo
hg ci -m1
hg co -q 0
echo dirty > foo
hg up -c
hg up -q
cat foo
hg st -A

echo '% validate update of standalone execute bit change'
hg up -C 0
chmod -x foo
hg ci -m removeexec
hg up -C 0
hg up
hg st
