#!/bin/sh

hg init
echo a > a
hg add a
hg commit -m "test" -d "0 0"
hg history
hg tag -d "0 0" "bleah"
hg history

echo foo >> .hgtags
hg tag -d "0 0" "bleah2" || echo "failed"

hg tag -l 'xx
newline'
hg tag -l 'xx:xx'
true
