#!/bin/sh

"$TESTDIR/hghave" no-symlink || exit 80

# The following script was used to create the bundle:
#
# hg init symlinks
# cd symlinks
# echo a > a
# mkdir d
# echo b > d/b
# ln -s a a.lnk
# ln -s d/b d/b.lnk
# hg ci -Am t
# hg bundle --base null ../test-no-symlinks.hg

# Extract a symlink on a platform not supporting them
echo % unbundle
hg init t
cd t
hg pull -q "$TESTDIR/test-no-symlinks.hg"
hg update

cat a.lnk && echo
cat d/b.lnk && echo

# Copy a symlink and move another
echo % move and copy
hg copy a.lnk d/a2.lnk
hg mv d/b.lnk b2.lnk
hg ci -Am copy
cat d/a2.lnk && echo
cat b2.lnk && echo

# Bundle and extract again
echo % bundle
hg bundle --base null ../symlinks.hg
cd ..

hg init t2
cd t2
hg pull ../symlinks.hg
hg update

cat a.lnk && echo
cat d/a2.lnk && echo
cat b2.lnk && echo
