#!/bin/sh

hg
hg -q
hg help
hg -q help

echo %% test short command list with verbose option
hg -v help shortlist | sed 's/[(]version [^)]*[)]/(version xxx)/'

hg add -h
hg add --skjdfks
hg help diff
hg help status
hg -q help status
hg help foo
hg skjdfks

exit 0
