#!/bin/sh -x
hg --debug init
echo this is a1 > a
hg add a
hg commit -t0 -d "0 0" -u user
echo this is b1 > b
hg add b
hg commit -t1 -d "0 0" -u user
hg manifest 1
echo this is c1 > c
hg rawcommit -p 1 -d "0 0" -u user -t2 c
hg manifest 2
hg parents
rm b
hg rawcommit -p 2 -d "0 0" -u user -t3 b
hg manifest 3
hg parents
echo this is a22 > a
hg rawcommit -p 3 -d "0 0" -u user -t4 a
hg manifest 4
hg parents
echo this is c22 > c
hg rawcommit -p 1 -d "0 0" -u user -t5 c
hg manifest 5
hg parents
# merge, but no files changed
hg rawcommit -p 4 -p 5 -d "0 0" -u user -t6
hg manifest 6
hg parents
# no changes what-so-ever
hg rawcommit -p 6 -d "0 0" -u user -t7
hg manifest 7
hg parents
