#!/bin/sh

hg init test
cd test
echo foo > foo
hg add foo
hg commit -d '0 0' -m commit-1
echo foo >> foo
hg commit -d '1 4444444' -m commit-3
hg commit -d '1	15.1' -m commit-4
hg commit -d 'foo bar' -m commit-5
hg commit -d ' 1 4444' -m commit-6
hg commit -d '111111111111 0' -m commit-7
exit 0
