#!/bin/sh

# Tests that the various help files are properly registered

echo "[extensions]" >> $HGRCPATH
echo "hggit=$(echo $(dirname $(dirname $0)))/hggit" >> $HGRCPATH

hg help | grep 'git' | sed 's/  */ /g'
hg help hggit | grep 'help git' | sed 's/:hg:`help git`/"hg help git"/g'
hg help git | grep 'Working with Git Repositories'
