#!/bin/sh

"$TESTDIR/hghave" execbit || exit 80

hg init
echo a > a
hg ci -d'0 0' -Am'not executable'

chmod +x a
hg ci -d'1 0' -m'executable'
hg id

hg up 0
hg id
test -x a && echo executable -- eek || echo not executable -- whew
