#!/bin/sh

echo % test --time
hg --time help -q help 2>&1 | grep Time > /dev/null || echo --time failed

echo % test --profile
if "$TESTDIR/hghave" -q lsprof; then
    hg --profile help -q help 2>&1 | grep CallCount > /dev/null || echo --profile failed
fi
