#!/bin/sh

# test that a commit clears the merge state.

hg init repo
cd repo

echo foo > file
hg commit -Am 'add file'

echo bar >> file
hg commit -Am 'append bar'

echo % create a second head
hg up -C 0
echo baz >> file
hg commit -Am 'append baz'

echo % failing merge
HGMERGE=internal:fail hg merge

echo resolved > file
hg resolve -m file
hg commit -m 'resolved'

echo % resolve -l, should be empty
hg resolve -l

# test crashed merge with empty mergestate
mkdir .hg/merge
touch .hg/merge/state
echo % resolve -l, should be empty
hg resolve -l
