#!/bin/sh

# test update logic when there are renames


# update with local changes across a file rename
hg init a
cd a
echo a > a
hg add a
hg ci -m a
hg mv a b
hg ci -m rename
echo b > b
hg ci -m change
hg up -q 0
echo c > a
hg up
cd ..
