#!/bin/sh

hg init
echo 123 > a
echo 123 > c
echo 123 > e
hg add a c e
hg commit -m "first" -d "1000000 0" a c e
echo 123 > b
echo %% should show b unknown
hg status
echo 12 > c
echo %% should show b unknown and c modified
hg status
hg add b
echo %% should show b added and c modified
hg status
hg rm a
echo %% should show a removed, b added and c modified
hg status
hg revert a
echo %% should show b added, copy saved, and c modified
hg status
hg revert b
echo %% should show b unknown, b.orig unknown, and c modified
hg status
hg revert --no-backup c
echo %% should show unknown: b b.orig
hg status
echo %% should show a b b.orig c e
ls
echo %% should verbosely save backup to e.orig
echo z > e
hg revert -v
echo %% should say no changes needed
hg revert a
echo %% should say file not managed
echo q > q
hg revert q
rm q
echo %% should say file not found
hg revert notfound
hg rm a
hg commit -m "second" -d "1000000 0"
echo z > z
hg add z
hg st
echo %% should add a, forget z
hg revert -r0
echo %% should forget a
hg revert -rtip
rm -f a *.orig
echo %% should silently add a
hg revert -r0 a
hg st a

true
