#!/bin/sh

"$TESTDIR/hghave" svn svn-bindings || exit 80

fix_path()
{
    tr '\\' /
}

echo "[extensions]" >> $HGRCPATH
echo "convert = " >> $HGRCPATH

svnadmin create svn-repo

echo % initial svn import
mkdir t
cd t
echo a > a
cd ..

svnpath=`pwd | fix_path`
# SVN wants all paths to start with a slash. Unfortunately,
# Windows ones don't. Handle that.
expr $svnpath : "\/" > /dev/null
if [ $? -ne 0 ]; then
    svnpath='/'$svnpath
fi

svnurl=file://$svnpath/svn-repo/trunk
svn import -m init t $svnurl | fix_path

echo % update svn repository
svn co $svnurl t2 | fix_path
cd t2
echo b >> a
echo b > b
svn add b
svn ci -m changea
cd ..

echo % convert to hg once
hg convert $svnurl

echo % update svn repository again
cd t2
echo c >> a
echo c >> b
svn ci -m changeb
cd ..

echo % test incremental conversion
hg convert $svnurl

