#!/bin/sh

echo 'syntax error' > badext.py
abspath=`pwd`/badext.py

echo '[extensions]' >> $HGRCPATH
echo "gpg =" >> $HGRCPATH
echo "hgext.gpg =" >> $HGRCPATH
echo "badext = $abspath" >> $HGRCPATH

hg -q help help
