#!/bin/sh

. "$TESTDIR/bzr-definitions"

cat > treeset.py <<EOF
import sys
from bzrlib import workingtree
wt = workingtree.WorkingTree.open('.')

message, rootid = sys.argv[1:]
wt.set_root_id('tree_root-%s' % rootid)
wt.commit(message)
EOF

echo % change the id of the tree root
mkdir test-change-treeroot-id
cd test-change-treeroot-id
bzr init -q source
cd source
echo content > file
bzr add -q file
bzr commit -q -m 'Initial add'
python ../../treeset.py 'Changed root' new
cd ..
hg convert source source-hg
manifest source-hg tip
