#!/bin/sh

hg init a
cd a
echo a > foo
hg add foo
hg commit -m 1 -d "1000000 0"
hg remove
rm foo
hg remove foo
hg revert
rm foo
hg remove --after
hg commit -m 2 -d "1000000 0"
hg export 0
hg export 1
hg log -p -r 0
hg log -p -r 1

cd ..
hg clone a b
