#!/bin/sh

hg init repo
cd repo
echo foo > foo
hg ci -qAm 'add foo' -d '0 0'
echo >> foo
hg ci -m 'change foo' -d '0 0'
hg up -qC 0
echo bar > bar
hg ci -qAm 'add bar' -d '0 0'
hg log
cd ..
hg init copy
cd copy

echo '% pull a missing revision'
hg pull -qr missing ../repo

echo '% pull -r 0'
hg pull -qr 0 ../repo
hg log

echo '% pull -r 1'
hg pull -qr 1 ../repo
hg log

# this used to abort: received changelog group is empty
echo '% pull -r 1 again'
hg pull -qr 1 ../repo
