#!/bin/sh

"$TESTDIR/hghave" rst2html || exit 80
RST2HTML=$(which rst2html 2> /dev/null || which rst2html.py)

echo "checking for syntax errors in gendoc.py"
python $TESTDIR/../doc/gendoc.py > gendoc.txt || exit

# We run rst2html over the file without adding "--halt warning" to
# make it report all errors instead of stopping on the first one.
echo "checking for parse errors with rst2html"
$RST2HTML gendoc.txt /dev/null
