#!/bin/sh

export HGMERGE=true

set -ex
mkdir r1
cd r1
hg init
echo a > a
hg addremove
hg commit -t "1" -u test -d "0 0"

hg clone . ../r2
cd ../r2
hg up
echo abc > a
hg diff > ../d
sed "s/\(\(---\|+++\).*\)\t.*/\1/" < ../d

cd ../r1
echo b > b
echo a2 > a
hg addremove
hg commit -t "2" -u test -d "0 0"

cd ../r2
hg -q pull ../r1
hg status
hg --debug up
hg --debug up -m
hg parents
hg -v history
hg diff > ../d
sed "s/\(\(---\|+++\).*\)\t.*/\1/" < ../d

