#!/bin/sh
hg init
echo This is file a1 > a
hg add a
hg commit -m "commit #0" -d "1000000 0"
ls
echo This is file b1 > b
hg add b
hg commit -m "commit #1" -d "1000000 0"
hg co 0
# B should disappear
ls
