#!/bin/sh

. $TESTDIR/helpers.sh

echo "[extensions]" >> $HGRCPATH
echo "graphlog=" >> $HGRCPATH
echo "rebase=" >> $HGRCPATH

rm -rf repo
hg init repo
cd repo

echo A > a
echo >> a
hg commit -AmA -u test -d '0 0'

echo B > a
echo >> a
hg commit -mB -u test -d '1 0'

echo C > a
echo >> a
hg commit -mC -u test -d '2 0'

hg up -C 0
echo D >> a
hg commit -AmAD -u test -d '3 0'

hg glog --template '{rev}:{desc} {node|short}\n'
hg rebase -q -s 1 -d 3 | hidebackup
hg glog --template '{rev}:{desc} {node|short}\n'

exit 0
