#!/bin/sh

hg init
echo "nothing" > a
hg add a
hg commit -m ancestor -d "0 0"
echo "something" > a
hg commit -m branch1 -d "0 0"
hg co 0
echo "something else" > a
hg commit -m branch2 -d "0 0"
HGMERGE=merge; export HGMERGE
hg up -m 1
hg id
egrep -v ">>>|<<<" a
hg status
