#!/bin/sh

mkdir a
cd a
hg init
echo a > a
hg add a
hg commit -m test -d '0 0'

# Default operation
hg clone . ../b
cd ../b
cat a
hg verify

# No update
hg clone -U . ../c
cd ../c
cat a 2>/dev/null || echo "a not present"
hg verify

# Default destination
mkdir ../d
cd ../d
hg clone ../a
cd a
hg cat a

# check that we drop the file:// from the path before
# writing the .hgrc
cd ../..
hg clone file://a e
grep 'file:' e/.hg/hgrc

# check that path aliases are expanded
hg clone -q -U --config 'paths.foobar=a#0' foobar f
hg -R f showconfig paths.default | sed -e 's,.*/,,'

exit 0
