#!/bin/sh

mkdir t
cd t
hg init

mkdir a
echo foo > a/a
echo bar > a/b
hg ci -Am "0"

hg co -C 0
hg mv a b
hg ci -m "1 mv a/ b/"

hg co -C 0
echo baz > a/c
echo quux > a/d
hg add a/c
hg ci -m "2 add a/c"

hg merge --debug 1
echo a/* b/*
hg st -C
hg ci -m "3 merge 2+1"
hg debugrename b/c

hg co -C 1
hg merge --debug 2
echo a/* b/*
hg st -C
hg ci -m "4 merge 1+2"
hg debugrename b/c
