#!/bin/sh

hg init repo
cd repo
cat > a <<EOF
c
c
a
a
b
a
a
c
c
EOF
hg ci -Am adda
cat > a <<EOF
c
c
a
a
dd
a
a
c
c
EOF

echo '% default context'
hg diff --nodates

echo '% invalid --unified'
hg diff --nodates -U foo

echo '% --unified=2'
hg diff --nodates -U 2

echo '% diff.unified=2'
hg --config diff.unified=2 diff --nodates

echo '% diff.unified=2 --unified=1'
hg diff --nodates -U 1

echo '% invalid diff.unified'
hg --config diff.unified=foo diff --nodates

exit 0


