#!/bin/sh

"$TESTDIR/hghave" symlink || exit 80

cleanpath()
{
    sed -e "s:/.*\(/test-symlink-basic/.*\):...\1:"
}

hg init a
cd a
ln -s nothing dangling
hg commit -m 'commit symlink without adding' -d '0 0' dangling 2>&1 | cleanpath
hg add dangling
hg commit -m 'add symlink' -d '0 0'

hg tip -v
hg manifest --debug
echo '% rev 0:'
$TESTDIR/readlink.py dangling

rm dangling
ln -s void dangling
hg commit -m 'change symlink'
echo '% rev 1:'
$TESTDIR/readlink.py dangling

echo '% modifying link'
rm dangling
ln -s empty dangling
$TESTDIR/readlink.py dangling

echo '% reverting to rev 0:'
hg revert -r 0 -a
$TESTDIR/readlink.py dangling

echo '% backups:'
$TESTDIR/readlink.py *.orig

rm *.orig
hg up -C
echo '% copies'
hg cp -v dangling dangling2
hg st -Cmard
$TESTDIR/readlink.py dangling dangling2
