#!/bin/sh
# test command parsing and dispatch

"$TESTDIR/hghave" no-outer-repo || exit 80

dir=`pwd`

hg init a
cd a
echo a > a
hg ci -Ama

echo "# missing arg"
hg cat

echo '% [defaults]'
hg cat a
cat >> $HGRCPATH <<EOF
[defaults]
cat = -r null
EOF
hg cat a

echo '% working directory removed'
sh -c "cd $dir && rm -rf a"
hg --version 2>&1 | sed -e 's,\(abort:.*:\).*$,\1 ...,g'

echo '% no repo'
cd $dir
hg cat

exit 0

