[package]
name = "pyconflict"
version = "0.1.0"
edition = "2018"

[dependencies]
conflict = { path = "../../../../lib/conflict", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
cpython = { version = "0.5", default-features = false }
types = { path = "../../../../lib/types", default-features = false }
serde_cbor = "0.11"

[features]
default = []
python2 = ["cpython/python27-sys", "cpython_ext/python2"]
python3 = ["cpython/python3-sys", "cpython_ext/python3"]
