load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "derived-data-service",
    dott_files = glob(["test-derived-data-service*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/facebook/derived_data_service:2ds_client",
        "//eden/mononoke/facebook/derived_data_service:derivation_worker",
        "//eden/mononoke/facebook/derived_data_service:derived_data_service",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/facebook/backfill_bonsai_blob_mapping:backfill_bonsai_blob_mapping",
        "//eden/mononoke/tools/testtool:testtool",
        "//zeus/zelos/interactive_cli:zeloscli",
    ],
)

dott_test(
    name = "derived-data-tailer",
    dott_files = glob(["test-derived-data-tailer*.t"]),
    deps = [
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/facebook/derived_data_tailer:derived_data_tailer",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
