[package]
name = "backsyncer"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/lib.rs", "src/main.rs", "src/tests.rs"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "backsyncer_cmd"
path = "src/main.rs"

[dependencies]
blobrepo = { path = "../../blobrepo" }
blobrepo_factory = { path = "../../blobrepo/factory" }
blobrepo_hg = { path = "../../blobrepo/blobrepo_hg" }
blobstore_factory = { path = "../../blobstore/factory" }
bookmarks = { path = "../../bookmarks" }
cmdlib = { path = "../../cmdlib" }
cmdlib_x_repo = { path = "../../cmdlib/x_repo" }
context = { path = "../../server/context" }
cross_repo_sync = { path = "../cross_repo_sync" }
live_commit_sync_config = { path = "../live_commit_sync_config" }
mercurial_types = { path = "../../mercurial/types" }
metaconfig_types = { path = "../../metaconfig/types" }
mononoke_types = { path = "../../mononoke_types" }
mutable_counters = { path = "../../mutable_counters" }
scuba_ext = { path = "../../common/scuba_ext" }
sql_construct = { path = "../../common/sql_construct" }
sql_ext = { path = "../../common/rust/sql_ext" }
synced_commit_mapping = { path = "../synced_commit_mapping" }
cached_config = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
clap = "2.33"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
slog = { version = "2.5", features = ["max_level_debug"] }
thiserror = "1.0"
tokio = { version = "=0.2.13", features = ["full"] }

[dev-dependencies]
blobrepo_override = { path = "../../blobrepo/override" }
blobstore = { path = "../../blobstore" }
bookmark_renaming = { path = "../bookmark_renaming" }
dbbookmarks = { path = "../../bookmarks/dbbookmarks" }
filestore = { path = "../../filestore" }
fixtures = { path = "../../tests/fixtures" }
manifest = { path = "../../manifest" }
movers = { path = "../movers" }
revset = { path = "../../revset" }
skiplist = { path = "../../reachabilityindex/skiplist" }
tests_utils = { path = "../../tests/utils" }
futures_ext = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
maplit = "1.0"
pretty_assertions = "0.6"
tokio-compat = "0.1"
