load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "cats",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:http",
        "//common/rust/shed/fbinit:fbinit",
        "//crypto/cat/rust:cryptocat",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/permission_checker:permission_checker",
    ],
)
