load("@fbsource//xplat/thrift:defs.bzl", "thrift_rust_library")

oncall("rust_foundation")

thrift_rust_library(
    name = "fbthrift_conformance",
    srcs = glob(
        [
            "src/*.rs",
        ],
    ),
    allow_oss_build = False,
    # Temporarily disabled while we optimize testset build time.
    # https://fb.workplace.com/groups/rust.language/posts/29013945748227331
    unittests = False,
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:hex",
        "fbsource//third-party/rust:itertools",
        "//thrift/conformance/if:any-rust",
        "//thrift/conformance/if:protocol-rust",
        "//thrift/lib/rust:fbthrift",
        "//thrift/lib/rust/universal_name:universal_name",
    ],
)
