load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "hooks",
    dott_files = glob([
        "test-hook-*.t",
    ]),
    deps = [
        "//common/tools/thriftdbg:thriftdbg",
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/testtool:testtool",
        "//signedsources:fixtures",
    ],
)
