load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*Test.cpp"]),
    compatible_with = [
        "ovr_config//os:linux",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//eden/common/telemetry:log_info",
        "//eden/common/utils:case_sensitivity",
        "//eden/common/utils:enum",
        "//eden/common/utils:process_info_cache",
        "//eden/fs/config:config",
        "//eden/fs/fuse:fuse",
        "//eden/fs/telemetry:error_logger",
        "//eden/fs/telemetry:stats",
        "//eden/fs/telemetry/test:capturing_scribe_logger",
        "//eden/fs/testharness:fake_fuse",
        "//eden/fs/testharness:test_dispatcher",
        "//folly:file",
        "//folly:random",
        "//folly/executors:global_executor",
        "//folly/test:test_utils",
    ],
)
