load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pyfs",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/fsinfo:fsinfo",
        "//eden/scm/lib/util/win32-8dot3:win32-8dot3",
    ],
)
