load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "cross-repo",
    dott_files = glob(["*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/features/commit_rewriting/backsyncer:backsyncer_cmd",
        "//eden/mononoke/features/commit_rewriting/commit_validator:commit_validator",
        "//eden/mononoke/features/commit_rewriting/mononoke_x_repo_sync_job:mononoke_x_repo_sync_job",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/servers/git/git_server:git_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
