// @generated SignedSource<<6d27f4341e90d8cd9c066b6e85a74100>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/redaction/redaction_set.thrift
include "thrift/annotation/rust.thrift"

@rust.Exhaustive
struct RedactionSet {
  // SEV or task with more information on why this was redacted
  1: string reason;
  // Id to the redaction key list, used to find it in the blobstore
  2: string id;
  // If false, don't actually redact keys, only log when they are accessed
  3: bool enforce = true;
}

@rust.Exhaustive
struct RedactionSets {
  // List of all redaction sets
  1: list<RedactionSet> all_redactions;
}
