mutation CreatePendingPullRequestReview($pullRequestId: ID!, $commitOid: GitObjectID!) {
  addPullRequestReview(input: {pullRequestId: $pullRequestId, commitOID: $commitOid}) {
    pullRequestReview {
      id
    }
  }
}

mutation CreateSubmittedPullRequestReview(
  $pullRequestId: ID!
  $event: PullRequestReviewEvent!
  $body: String
) {
  addPullRequestReview(input: {pullRequestId: $pullRequestId, event: $event, body: $body}) {
    pullRequestReview {
      id
    }
  }
}

mutation AddPullRequestReviewThread(
  $pullRequestReviewId: ID!
  $body: String!
  $path: String!
  $line: Int!
  $side: DiffSide!
  $startLine: Int
  $startSide: DiffSide
) {
  addPullRequestReviewThread(
    input: {
      pullRequestReviewId: $pullRequestReviewId
      body: $body
      path: $path
      line: $line
      side: $side
      startLine: $startLine
      startSide: $startSide
    }
  ) {
    thread {
      id
    }
  }
}

mutation SubmitPullRequestReview(
  $pullRequestReviewId: ID!
  $event: PullRequestReviewEvent!
  $body: String
) {
  submitPullRequestReview(
    input: {pullRequestReviewId: $pullRequestReviewId, event: $event, body: $body}
  ) {
    pullRequestReview {
      id
    }
  }
}

mutation ResolvePullRequestReviewThread($threadId: ID!) {
  resolveReviewThread(input: {threadId: $threadId}) {
    thread {
      id
      isResolved
    }
  }
}

mutation UnresolvePullRequestReviewThread($threadId: ID!) {
  unresolveReviewThread(input: {threadId: $threadId}) {
    thread {
      id
      isResolved
    }
  }
}
