load("@fbsource//tools/target_determinator/macros:ci_hint.bzl", "ci_hint")
load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

# Test suit for testing of Mononoke CAS Sync and also
# for testing Sapling/Cas integration when a repo is synced

dott_test(
    name = "mononoke_re_cas",
    dott_files = glob([
        "*.t",
    ]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/jobs/cas_sync:mononoke_cas_sync_job",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

# This adds some artificial direct dependecies to CI graph to make it look like deps are closer
ci_hint(
    ci_deps = [
        "fbcode//cas/client_lib/wrappers/rust:cas_client_lib",
        "fbcode//cas/client_lib/wrappers/rust/casd_only_client:cas_client_lib",
    ],
    reason = "Those tests should be triggered on RE diffs despite the longer CI distance",
    target = "mononoke_re_cas",
)
