[package]
name = "regenerate_hg_filenodes"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
blobrepo = { path = "../blobrepo" }
blobrepo_hg = { path = "../blobrepo/blobrepo_hg" }
blobrepo_override = { path = "../blobrepo/override" }
blobstore = { path = "../blobstore" }
cacheblob = { path = "../blobstore/cacheblob" }
cmdlib = { path = "../cmdlib" }
context = { path = "../server/context" }
derived_data_filenodes = { path = "../derived_data/filenodes" }
mercurial_types = { path = "../mercurial/types" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
