// @generated SignedSource<<8c0d2cf9846d5070a28da4f7ec877da1>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/lfs_server/lfs_server.thrift

include "configerator/structs/scm/mononoke/ratelimiting/ratelimits.thrift"

struct ObjectPopularity {
  // The SCS category used to record object popularity.
  1: string category;
  // The window (in seconds) over which an object's popularity is calculated.
  2: i32 window;
  // If more than <threshold> bytes of an object have been served in <window>
  // time, then it is considered as popular.
  3: i64 threshold;
} (rust.exhaustive)

struct LfsServerConfig {
  // Whether or not to increment counters when sending bytes as opposed to when
  // accepting an upload.
  1: bool track_bytes_sent;

  // Whether or not to emit ?routing=SHA256 query strings when respond to a
  // batch request.
  2: bool enable_consistent_routing;

  // Don't use 3 and 4: these were used in the past.

  // 5: deleted

  // 6: deleted

  // Whether to enforce ACL checks.
  7: bool enforce_acl_check;

  // Whether to skip client hostname resolution and logging.
  8: bool disable_hostname_logging;

  // 9: deleted

  // 10: deleted

  11: optional ObjectPopularity object_popularity;

  // The number of tasks to receive given content.
  12: i16 tasks_per_content;

  // Disable compression of blob downloads for all clients
  13: bool disable_compression;

  // Disable compression of blob downloads for clients with the specified
  // identities. The client's identities are compared to each of the identity
  // lists specified. If one of the identity lists is a subset of the client's
  // identity then compression will be disabled.
  14: list<list<string>> disable_compression_identities;

  // Whether to enforce certificate presence.
  15: bool enforce_authentication;

  // Load shedding config
  16: list<ratelimits.LoadShedLimit> loadshedding_limits;
} (rust.exhaustive)
