load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "mononoke_repos",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/common/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:parking_lot",
    ],
)
