/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

export type TrackEventName =
  | 'ClickedRefresh'
  | 'ClientConnection'
  | 'LoadMoreCommits'
  | 'RunOperation'
  | 'StarRating'
  | 'TopLevelErrorShown'
  | 'UIEmptyState'
  | 'HeadCommitChanged'
  | 'AbortMergeOperation'
  | 'PullOperation'
  | 'AbortMergeOperation'
  | 'AddOperation'
  | 'AddRemoveOperation'
  | 'AmendMessageOperation'
  | 'AmendOperation'
  | 'CommitOperation'
  | 'ContinueMergeOperation'
  | 'CreateEmptyInitialCommit'
  | 'DiscardOperation'
  | 'ForgetOperation'
  | 'GettingStartedInteraction'
  | 'GhStackSubmitOperation'
  | 'GotoOperation'
  | 'GoBackToOldISL'
  | 'GoBackToOldISLOnce'
  | 'GoBackToOldISLReason'
  | 'HideOperation'
  | 'ImportStackOperation'
  | 'PrSubmitOperation'
  | 'PullOperation'
  | 'PurgeOperation'
  | 'RebaseOperation'
  | 'ResolveOperation'
  | 'RevertOperation'
  | 'SetConfigOperation'
  | 'ShowBugButtonNux'
  | 'StackEditMetrics'
  | 'UncommitOperation'
  // @fb-only
  | 'OptimisticFilesStateForceResolved'
  | 'OptimisticCommitsStateForceResolved'
  | 'OptimisticConflictsStateForceResolved'
  | 'OptInToNewISLAgain'
  | 'QueueOperation'
  | 'UnsubmittedStarRating'
  | 'UploadImage'
  | 'RunVSCodeCommand'
  | 'UnsubmittedStarRating'
  | 'VSCodeExtensionActivated';

export type TrackErrorName =
  | 'DiffFetchFailed'
  | 'InvalidCwd'
  | 'InvalidCommand'
  | 'GhCliNotAuthenticated'
  | 'GhCliNotInstalled'
  | 'TopLevelError'
  | 'RunOperationError'
  | 'RepositoryError'
  | 'UploadImageError'
  | 'VSCodeCommandError'
  | 'VSCodeActivationError';
