load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "dedupmap",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/mononoke_macros:mononoke_macros"],
)
