load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "quiet_stream",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:pin-project",
        "fbsource//third-party/rust:tokio",
    ],
)
