load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "sshrelay",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tokio-util",
        "fbsource//third-party/rust:zstd",
        "fbsource//third-party/rust:zstd-safe",
        "//common/rust/shed/netstring:netstring",
        "//eden/mononoke/common/metadata:metadata",
    ],
)
