load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("sapling")

rust_binary(
    name = "codegen-exe",
    srcs = [
        "src/main.rs",
    ],
    crate_root = "src/main.rs",
    deps = [
        "//eden/scm/lib/python-modules/codegen:codegen",
    ],
)
