load("//eden/scm:targets.bzl", "sl_rust_binary")

oncall("sapling")

sl_rust_binary(
    name = "codegen-exe",
    srcs = [
        "src/main.rs",
    ],
    crate_root = "src/main.rs",
    deps = [
        "//eden/scm/lib/python-modules/codegen:codegen",
    ],
)
