load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("scm_server_infra")

rust_library(
    name = "bonsai_svnrev_mapping",
    srcs = glob([
        "src/**/*.rs",
        "schemas/**/*.sql",
    ]),
    named_deps = {
        "bincode": "fbsource//third-party/rust:bincode-2",
        "slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat",
    },
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:thiserror",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/memcache_stub:memcache",
        "//eden/mononoke/bonsai_svnrev_mapping/if:bonsai_svnrev_mapping_thrift-rust",
        "//eden/mononoke/common/rust/caching_ext:caching_ext",
        "//eden/mononoke/common/rust/sql_ext:sql_ext",
        "//eden/mononoke/common/sql_construct:sql_construct",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/server/context:context",
        "//thrift/lib/rust:fbthrift",
    ],
)

rust_unittest(
    name = "bonsai_svnrev_mapping_test",
    srcs = glob(["test/**/*.rs"]),
    crate = "bonsai_svnrev_mapping_test",
    deps = [
        "fbsource//third-party/rust:anyhow",
        ":bonsai_svnrev_mapping",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//eden/mononoke/common/sql_construct:sql_construct",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
        "//eden/mononoke/mononoke_types:mononoke_types-mocks",
        "//eden/mononoke/server/context:context",
    ],
)
