load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pydag",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:parking_lot",
        "//eden/scm/lib/async-runtime:async-runtime",
        "//eden/scm/lib/commits:commits",
        "//eden/scm/lib/config/model:configmodel",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/dag:dag",
        "//eden/scm/lib/edenapi/types:edenapi_types",
        "//eden/scm/lib/minibytes:minibytes",
        "//eden/scm/lib/storemodel:storemodel",
        "//eden/scm/lib/types:types",
        "//eden/scm/saplingnative/bindings/modules/pyedenapi:pyedenapi",
        "//eden/scm/saplingnative/bindings/modules/pyformatutil:pyformatutil",
        "//eden/scm/saplingnative/bindings/modules/pyio:pyio",
        "//eden/scm/saplingnative/bindings/modules/pymetalog:pymetalog",
    ],
)
