[package]
name = "blobstore"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs", "test/**/*.rs"]

[lib]
path = "src/lib.rs"

[[test]]
name = "blobstore_test"
path = "test/main.rs"

[dependencies]
context = { path = "../server/context" }
stats = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
abomonation = "0.7"
abomonation_derive = "0.5"
anyhow = "1.0"
auto_impl = "0.4"
bytes = { version = "0.5", features = ["serde"] }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
thiserror = "1.0"
zstd = "=0.4.23"

[dev-dependencies]
cacheblob = { path = "cacheblob" }
fileblob = { path = "fileblob" }
memblob = { path = "memblob" }
mononoke_types = { path = "../mononoke_types" }
fbinit = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
tempdir = "0.3"
tokio-compat = "0.1"
