load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("scm_server_infra")

thrift_library(
    name = "git-types-thrift",
    languages = [
        "rust",
        "cpp2",
    ],
    rust_deps = [
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:smallvec",
    ],
    thrift_rust_options = ["default_enum_zero"],
    thrift_srcs = {"git_types_thrift.thrift": []},
    deps = [
        "//eden/mononoke/mononoke_types/serialization:mononoke_types_serialization",
        "//thrift/annotation:rust",
        "//thrift/annotation:thrift",
    ],
)
