load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pystoremodel",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:serde",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/storemodel:storemodel",
        "//eden/scm/lib/types:types",
    ],
)
