load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "gitbundle",
    dott_files =
        glob([
            "*.t",
        ]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
