load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("scm_server_infra")

thrift_library(
    name = "bonsai_git_mapping_entry_thrift",
    languages = [
        "rust",
    ],
    rust_deps = [
        "fbsource//third-party/rust:smallvec",
    ],
    thrift_srcs = {
        "bonsai_git_mapping.thrift": [],
    },
    # The Thrift definitions are private and only used for serialization -- do
    # not allow other code to use them.
    visibility = [
        "//eden/mononoke/repo_attributes/bonsai_git_mapping:bonsai_git_mapping",
        "//eden/mononoke/repo_attributes/bonsai_git_mapping:bonsai_git_mapping-unittest",
    ],
    deps = [
        "//eden/mononoke/mononoke_types/serialization:mononoke_types_serialization",
        "//thrift/annotation:rust",
        "//thrift/annotation:thrift",
    ],
)
