[package]
name = "cross_repo_sync_test_utils"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
blobrepo = { path = "../../../blobrepo" }
blobrepo_factory = { path = "../../../blobrepo/factory" }
blobrepo_hg = { path = "../../../blobrepo/blobrepo_hg" }
blobstore = { path = "../../../blobstore" }
bookmarks = { path = "../../../bookmarks" }
context = { path = "../../../server/context" }
cross_repo_sync = { path = ".." }
megarepolib = { path = "../../megarepo" }
metaconfig_types = { path = "../../../metaconfig/types" }
mononoke_types = { path = "../../../mononoke_types" }
sql_construct = { path = "../../../common/sql_construct" }
sql_ext = { path = "../../../common/rust/sql_ext" }
synced_commit_mapping = { path = "../../synced_commit_mapping" }
tests_utils = { path = "../../../tests/utils" }
cloned = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
sql = { git = "https://github.com/facebookexperimental/rust-shed.git", branch = "master" }
anyhow = "1.0"
ascii = "1.0"
futures = { version = "0.3.5", features = ["async-await", "compat"] }
maplit = "1.0"
