load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "hooks",
    dott_files = glob(
        [
            "*.t",
        ],
    ),
    enable_remote_execution = True,
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
