load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*Test.cpp"]),
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//eden/common/utils:bug",
        "//eden/common/utils:file_utils",
        "//eden/common/utils:path",
        "//eden/fs/config:config",
        "//eden/fs/model/git:gitignore",
        "//folly:file",
        "//folly:file_util",
        "//folly:range",
        "//folly/test:test_utils",
        "//folly/testing:test_util",
    ],
    external_deps = [
        ("boost", None, "boost_algorithm"),
    ],
)
