load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "admin",
    dott_files = glob(["test-admin-*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/facebook/backfill_bonsai_blob_mapping:backfill_bonsai_blob_mapping",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
