load("@fbcode_macros//build_defs:rust_binary.bzl", "rust_binary")
load("//fbpkg:fbpkg.bzl", "fbpkg")

oncall("scm_server_infra")

rust_binary(
    name = "derived_data_tailer",
    srcs = glob([
        "src/**/*.rs",
    ]),
    named_deps = {"slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat"},
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tokio",
        "//common/rust/fbwhoami:fbwhoami",
        "//common/rust/shed/borrowed:borrowed",
        "//common/rust/shed/cloned:cloned",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/futures_stats:futures_stats",
        "//common/rust/shed/justknobs_stub:justknobs",
        "//common/rust/smc-thrift:smc-thrift",
        "//eden/mononoke/bookmarks:bookmarks",
        "//eden/mononoke/cmdlib/mononoke_app:mononoke_app",
        "//eden/mononoke/cmdlib/sharding:executor_lib",
        "//eden/mononoke/cmdlib/sharding_ext:sharding_ext",
        "//eden/mononoke/cmdlib/zk_leader_election:zk_leader_election",
        "//eden/mononoke/derived_data:bulk_derivation",
        "//eden/mononoke/derived_data:derived_data_manager",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_repos:mononoke_repos",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/repo_derived_data:repo_derived_data",
        "//eden/mononoke/repo_attributes/repo_identity:repo_identity",
        "//eden/mononoke/server/context:context",
    ],
)

fbpkg.builder(
    name = "mononoke.derived_data_tailer",
    path_actions = {
        "derived_data_tailer": ":derived_data_tailer",
    },
)
