load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "commit_graph_types",
    srcs = glob(["src/**/*.rs"]),
    named_deps = {"bincode": "fbsource//third-party/rust:bincode-2"},
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:maplit",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:smallvec",
        "fbsource//third-party/rust:vec1",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/commit_graph/commit_graph_types/if:commit_graph_thrift-rust",
        "//eden/mononoke/server/context:context",
    ],
)
