load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pybacktrace",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/backtrace-ext:backtrace-ext",
        "//eden/scm/lib/backtrace-python:backtrace-python",
    ],
)
