load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_infra")

dott_test(
    name = "gitexport",
    disable_all_network_access_target = False,
    dott_files = glob(
        ["*.t"],
    ),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/git/gitexport:gitexport",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
