load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "yield_stream",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:tokio",
    ],
    deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:pin-project",
    ],
)
