load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "cross-repo-and-scs",
    dott_files = glob([
        "test-cross-repo-and-scs-*.t",
    ]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/commit_rewriting/backsyncer:backsyncer_cmd",
        "//eden/mononoke/commit_rewriting/commit_validator:commit_validator",
        "//eden/mononoke/commit_rewriting/mononoke_x_repo_sync_job:mononoke_x_repo_sync_job",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/git_server:git_server",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
