load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")
load("@fbcode_macros//build_defs/lib:rust_oss.bzl", "rust_oss")

oncall("scm_server_infra")

rust_library(
    name = "sql_ext",
    srcs = glob([
        "src/**/*.rs",
    ]),
    named_deps = {
        "bincode": "fbsource//third-party/rust:bincode-2",
        "slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat",
    },
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
        "//eden/mononoke/server/metadata:metadata",
    ],
    deps = ([
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:base64",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:maplit",
        "fbsource//third-party/rust:paste",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_cbor",
        "//eden/mononoke/common/scuba_ext:scuba_ext",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:twox-hash",
        "//common/rust/mysql:mysql_client",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/justknobs_stub:justknobs",
        "//common/rust/shed/memcache_stub:memcache",
        "//common/rust/shed/sql:sql",
        "//dba/myadmin/if:if-myadmin-rust",
        "//dba/myadmin/if:if-myadmin-rust-srclients",
        "//eden/mononoke/common/rust/sql_ext/sql_query_telemetry:sql_query_telemetry",
        "//eden/mononoke/common/retry:retry",
        "//eden/mononoke/common/rust/caching_ext:caching_ext",
        "//eden/mononoke/repo_attributes/sql_query_config:sql_query_config",
        "//eden/scm/lib/clientinfo:clientinfo",
    ] + ([] if rust_oss.is_oss_build() else [
        "fbsource//third-party/rust:aws-config",
        "fbsource//third-party/rust:aws-sdk-secretsmanager",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:once_cell",
        "fbsource//third-party/rust:vec1",
        "//common/rust/shed/sql:sql_common",
        "//common/rust/shed/stats:stats",
        "fbsource//third-party/rust:mysql_async",
        "//eden/mononoke/common/time_measuring:time_measuring",
    ])) + [
        "//dba/myadmin/if:if-myadmin-rust-clients",
    ],
)
