load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*Test.cpp"]),
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//eden/common/utils:path",
        "//eden/fs/model:model",
        "//eden/fs/testharness:test_util",
        "//eden/fs/utils:eden_error",
        "//folly:range",
        "//folly:string",
        "//folly/container:array",
        "//folly/io:iobuf",
    ],
)
