load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "derivation_pipeline_driver",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {"cargo_toml_dir": "."},
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:futures",
        "//eden/mononoke/blobstore:blobstore",
        "//eden/mononoke/derived_data:bulk_derivation",
        "//eden/mononoke/derived_data:derived_data_manager",
        "//eden/mononoke/derived_data/derivation_pipeline_utils:derivation_pipeline_utils",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/repo_blobstore:repo_blobstore",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
    ],
)
