load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pyhgmetrics",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/hg-metrics:hg-metrics",
        "//eden/scm/lib/metrics:metrics",
        "//eden/scm/lib/sampling:sampling",
    ],
)
