load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "subtree",
    dott_files =
        glob(
            [
                "*.t",
            ],
        ),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/clients/scsc:scsc",
        "//eden/mononoke/servers/scs/scs_server:scs_server",
        "//eden/mononoke/tests/integration:urlencode",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
