load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("source_control")

thrift_library(
    name = "config",
    languages = [
        "py3-deprecated",
        "rust",
        "python",
        "cpp2",
    ],
    py3_namespace = "configerator",
    thrift_rust_options = "serde",
    thrift_srcs = {"hgclient.thrift": []},
    deps = [
        "//thrift/annotation:cpp",
        "//thrift/annotation:rust",
    ],
)
