load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pydirs",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:dirs",
        "//eden/scm/lib/cpython-ext:cpython-ext",
    ],
)
