// @generated SignedSource<<20a1f696f9ac36c2f48bca289e4fb375>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/github_mirror/github_mirror.thrift
//
// Source: https://www.internalfb.com/code/configerator/[master]/source/scm/mononoke/github_mirror/github_mirror.thrift
include "thrift/annotation/rust.thrift"
include "thrift/annotation/thrift.thrift"

@thrift.AllowLegacyMissingUris
package;

namespace py3 configerator.structs.scm.mononoke.github_mirror
namespace hack ConfigeratorScmMononokeGithubMirror

// How sync from GitHub to Mononoke is triggered for a given mirror.
//
// WEBHOOK_ONLY (the default when unset) is appropriate for the vast
// majority of mirrors. POLLING_ONLY and BOTH should be opt-in for
// specific repos because polling cost grows linearly with repo count
// and becomes meaningful at thousands-of-repos scale.
enum SyncTrigger {
  WEBHOOK_ONLY = 0,
  POLLING_ONLY = 1,
  BOTH = 2,
}

// Marker variant for ImportRefs::all. Empty by design -- its presence
// (not its content) is the signal.
@rust.Exhaustive
struct AllRefs {}

// Which refs to mirror. Either every ref (all branches and tags) or an
// explicit list of ref names (e.g., ["refs/heads/main", "refs/tags/v1"]).
//
// Modeled as a union so the "all" case is type-explicit instead of
// inferred from an empty list, and so additional selection modes (e.g.,
// glob patterns) can be added later as new variants without changing
// existing entries.
union ImportRefs {
  1: AllRefs all;
  2: list<string> specific;
}

// Per-repo metadata for a single GitHub-to-Mononoke mirror.
@rust.Exhaustive
struct GithubMirrorEntry {
  // Oncall name for the upstream team owning this repo.
  1: optional string owner_oncall;
  // When this entry was first added, Unix epoch seconds.
  2: optional i64 created_at_unix_seconds;
  // Trigger mode for syncing this mirror. Unset = WEBHOOK_ONLY.
  3: optional SyncTrigger sync_trigger;
  // Which refs to mirror -- either every ref or an explicit list.
  // Applied at fetch time as the git fetch refspec and passed to
  // gitimport's --include-refs for belt-and-suspenders filtering.
  4: ImportRefs import_refs;
}

// Registry of GitHub repos to mirror, keyed by repo name.
@rust.Exhaustive
struct GithubMirrorRegistry {
  1: map<string, GithubMirrorEntry> entries;
}

// Per-org mirror config. Pairs a GitHub org with its mirrored repos.
@rust.Exhaustive
struct GithubOrgMirrorRepos {
  // GitHub org name (e.g., "par-msl").
  1: string org;
  // GitHub App installation ID for this org.
  2: i64 installation_id;
  // Exact keychain secret name for this org's installation token
  // (e.g., "SCM_MIRROR_INSTALLATION_PAR_MSL").
  3: string installation_secret_name;
  // Repos mirrored under this org.
  4: GithubMirrorRegistry registry;
}

// Top-level config. Single GitHub App installed across multiple orgs.
@rust.Exhaustive
struct GithubMirrorAppRegistry {
  // GitHub App ID (public, assigned by GitHub at app creation time).
  1: i64 app_id;
  // Keychain secret name for the App's private key.
  2: string app_secret_name;
  // Per-org registries of mirrored repos.
  3: list<GithubOrgMirrorRepos> orgs;
}
