load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "lfs-server",
    # These tests have been vetted to run well without network access. Please investigate any failure thoroughly before disabling.
    disable_all_network_access_target = True,
    dott_files = glob(["*.t"]),
    deps = [
        "//eden/mononoke/lfs_server:lfs_server",
        "//eden/mononoke/tools/import:import",
    ],
)
