load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "backfill-derived",
    dott_files = glob(
        ["*.t"],
    ),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/backfill_mapping:backfill_mapping",
        "//eden/mononoke/tools/blobimport:blobimport",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
