load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_client_infra")

rust_library(
    name = "edenfs-error",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "//eden/fs/service:thrift-rust-thriftclients",
        "//eden/fs/service:thrift-streaming-rust-clients",
        "//eden/scm/lib/thrift-types:thrift-types",
    ],
)
