load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "connection_security_checker",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "//eden/mononoke/common/permission_checker:permission_checker",
        "//eden/mononoke/metaconfig:metaconfig_types",
    ],
)
