// @generated SignedSource<<74855fa1ff395370a9df788359795baf>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/tunables/tunables.thrift

/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This software may be used and distributed according to the terms of the
 * GNU General Public License version 2.
 */

namespace py configerator.mononoke.tunables

struct Tunables {
    1: map<string, bool> (rust.type = "HashMap") killswitches,
    2: map<string, i64> (rust.type = "HashMap") ints,
    3: map<string, string> (rust.type = "HashMap") strings,
}
