// @generated SignedSource<<8a9e39991322852d8342206a1e52cf43>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/tunables/tunables.thrift

/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This software may be used and distributed according to the terms of the
 * GNU General Public License version 2.
 */

namespace py configerator.mononoke.tunables

struct Tunables {
    1: map<string, bool> (rust.type = "HashMap") killswitches,
    2: map<string, i64> (rust.type = "HashMap") ints,
    3: map<string, string> (rust.type = "HashMap") strings,
    8: map<string, list<string>> (rust.type = "HashMap") vec_of_strings,

    4: optional map<string,  map<string, bool> (rust.type = "HashMap")> (rust.type = "HashMap") killswitches_by_repo,
    5: optional map<string, map<string, i64> (rust.type = "HashMap")> (rust.type = "HashMap") ints_by_repo,
    6: optional map<string, map<string, string> (rust.type = "HashMap")> (rust.type = "HashMap") strings_by_repo,
    7: optional map<string, map<string, list<string>> (rust.type = "HashMap")> (rust.type = "HashMap") vec_of_strings_by_repo,
} (rust.exhaustive)
