-- Looks for a BUCK file in the directory where `pbxproj_path` is and returns
-- it's content
local function get_matching_buck_file (ctx, pbxproj_path)
  local buck_path = pbxproj_path:match("(.*/)").."BUCK"
  return ctx.file_content(buck_path)
end

-- Checks if the buck file has a `xcode_project_config` rule with project_name
-- matching the name of the Xcode project in which this BUCK file is
local function check_config (buck_file, pbxproj_path)
  local project_name = pbxproj_path:match(
    "([^/]*)%.xcodeproj/project%.pbxproj$"
  )
  return buck_file:find(
    "xcode_project_config%(.-project_name%s*=%s*'"..project_name.."'.-%)"
  ) ~= nil
end

-- Don't accept diffs which change Xcode project files managed by Buck.
function hook (ctx)
  local modified_buck_projects = {}
  for _, file in ipairs(ctx.files) do
    if not file:is_deleted()
      and file.path:find('^fbobjc/.*%.xcodeproj/project%.pbxproj$')
    then
      local buck_file = get_matching_buck_file(ctx, file.path)
      if buck_file and check_config(buck_file, file.path) then
        modified_buck_projects[#modified_buck_projects + 1] = file.path
      end
    end
  end

  if #modified_buck_projects == 0 then
     -- modified_buck_projects is empty
     return true
  else
    local plural = ""
    local verb = "is"
    local pronoun = "it"

    if #modified_buck_projects >= 2 then
      -- there are at least 2 elements in table
      plural = "s"
      verb = "are"
      pronoun = "them"
    end

    modified_buck_projects = table.concat(modified_buck_projects, " ")

    return false, string.format(
      "The Xcode project%s at %s %s automatically generated by Buck. You"..
      " should NOT commit changes to %s. Add %s to .gitignore and .hgignore"..
      " and 'git rm' %s and try again. "..
      "If you're sure of the implications and want to commit a Buck-generated"..
      " project, add @ignore-buck-managed-project-files to a your commit"..
      " message.",
      plural,
      modified_buck_projects,
      verb,
      pronoun,
      modified_buck_projects,
      pronoun
    )
  end
end
