load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "bookmarks_types",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {"cargo_toml_dir": "."},
    test_deps = ["//eden/mononoke/common/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:ascii",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:quickcheck",
        "//common/rust/shed/ascii_ext:ascii_ext",
        "//common/rust/shed/quickcheck_arbitrary_derive:quickcheck_arbitrary_derive",
        "//common/rust/shed/sql:sql",
        "//eden/scm/lib/edenapi/types:edenapi_types",
    ],
)
