load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "scs-land-service",
    dott_files = glob(["test-scs-land*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/commit_rewriting/backsyncer:backsyncer_cmd",
        "//eden/mononoke/land_service/facebook/server:land_service",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
