load("@fbcode_macros//build_defs/lib:rust_oss.bzl", "rust_oss")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "cmdlib_caching",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["//eden/mononoke/common/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:clap",
        "//common/rust/shed/fbinit:fbinit",
        "//eden/mononoke/cmdlib:arg_extensions",
        "//eden/mononoke/cmdlib:environment",
    ]
    + (
        []
        if rust_oss.is_oss_build()
        else [
            "fbsource//third-party/rust:anyhow",
            "//common/rust/shed/cachelib_stub:cachelib",
        ]
    ),
)
