load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pyserde",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:serde_cbor",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:toml",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/mincode:mincode",
    ],
)
