load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "sql_telemetry_logger",
    srcs = [
        "sql_telemetry_logger.rs",
    ],
    deps = [
        "//common/rust/shed/fbinit:fbinit",
        "//eden/scm/lib/clientinfo:clientinfo",
    ],
)
