load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "scs",
    dott_files =
        glob([
            "*.t",
        ]),
    enable_async_requests_worker = True,
    deps = [
        "//eden/mononoke:backfill_mapping",
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/commit_rewriting/backsyncer:backsyncer_cmd",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
        "//metalos/facebook/fb303-status:fb303-status",
    ],
)
