load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "commit_id",
    srcs = glob(["src/*.rs"]),
    crate_root = "src/commit_id.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:strum",
        "//eden/mononoke/bookmarks:bookmarks",
        "//eden/mononoke/cmdlib/commit_id_types:commit_id_types",
        "//eden/mononoke/mercurial:mercurial_types",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/server/context:context",
    ],
)
