load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "modern_sync",
    # These tests have been vetted to run well without network access. Please investigate any failure thoroughly before disabling.
    disable_all_network_access_target = True,
    dott_files =
        glob([
            "*.t",
        ]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/modern_sync:mononoke_modern_sync_job",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
