load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "remote-gitimport",
    dott_files = glob(["test-remote-gitimport*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/git/facebook/git_move_bookmark:git_move_bookmark",
        "//eden/mononoke/git/facebook/remote_gitimport:remote_gitimport",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/lfs_server:lfs_server",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
    ],
)
