load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("scm_client_infra")

cpp_library(
    name = "sqlitetreestore",
    srcs = ["SqliteTreeStore.cpp"],
    headers = ["SqliteTreeStore.h"],
    deps = [
        "//eden/common/utils:utils",
        "//eden/fs/inodes:inode_number",
        "//eden/fs/inodes/overlay:serialization-cpp2-types",
        "//eden/fs/model:model",
        "//eden/fs/telemetry:log_info",
        "//eden/fs/telemetry:structured_logger",
        "//folly:range",
        "//folly:stop_watch",
        "//folly/logging:logging",
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/googletest:gtest_prod_headers",
        "//eden/common/utils:path",
        "//eden/fs/sqlite:sqlite",
    ],
)

cpp_library(
    name = "sqliteinodecatalog",
    srcs = [
        "SqliteInodeCatalog.cpp",
    ],
    headers = [
        "SqliteInodeCatalog.h",
    ],
    deps = [
        "//eden/common/utils:bug",
        "//eden/common/utils:utils",
        "//eden/fs/inodes:inode_number",
        "//eden/fs/inodes/overlay:serialization-cpp2-types",
        "//folly:file",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "//eden/fs/inodes/overlay:windows_fsck",
        ],
    }),
    exported_deps = [
        ":sqlitetreestore",
        "//eden/common/utils:path",
        "//eden/fs/inodes:inode_catalog",
        "//eden/fs/inodes/overlay:overlay_checker",
        "//folly:range",
    ],
)

cpp_library(
    name = "bufferedsqliteinodecatalog",
    srcs = [
        "BufferedSqliteInodeCatalog.cpp",
    ],
    headers = [
        "BufferedSqliteInodeCatalog.h",
    ],
    deps = [
        "//eden/fs/config:config",
        "//eden/fs/inodes:inode_number",
        "//folly/futures:core",
        "//folly/logging:logging",
        "//folly/system:thread_name",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gtest_prod_headers",
        ":sqliteinodecatalog",
        "//eden/fs/inodes/overlay:serialization-cpp2-types",
        "//folly:function",
        "//folly:synchronized",
        "//folly/synchronization:lifo_sem",
    ],
)

cpp_binary(
    name = "windows_overlay_scanner",
    srcs = ["WindowsOverlayScanner.cpp"],
    deps = [
        ":sqliteinodecatalog",
        "//eden/common/utils:path",
        "//eden/fs/config:config",
        "//eden/fs/inodes/overlay:overlay_checker",
        "//eden/fs/telemetry:structured_logger",
        "//eden/fs/utils:win_stacktrace",
        "//folly/init:init",
        "//folly/logging:init",
        "//folly/logging:logging",
    ],
    external_deps = [
        "gflags",
    ],
)
