load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pyrevisionstore",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:tracing",
        "//eden/scm/lib/blob:blob",
        "//eden/scm/lib/config/model:configmodel",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/revisionstore:revisionstore",
        "//eden/scm/lib/storemodel:storemodel",
        "//eden/scm/lib/types:types",
        "//eden/scm/saplingnative/bindings/modules/pyconfigloader:pyconfigloader",
    ],
)
