load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "wireproto_handler",
    srcs = glob(["src/**/*.rs"]),
    named_deps = {"slog": "//common/rust/shed/tracing_slog_compat:tracing_slog_compat"},
    deps = [
        "//common/rust/shed/facet:facet",
        "//eden/mononoke/bookmarks:bookmarks",
        "//eden/mononoke/commit_rewriting/synced_commit_mapping:synced_commit_mapping",
        "//eden/mononoke/common/scuba_ext:scuba_ext",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mutable_counters:mutable_counters",
    ],
)
