/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use cpython::Python;
use cpython::exc;
use util::path_error_details;

pub fn translate_io_error(py: Python, e: &std::io::Error) -> cpython::PyErr {
    if let Some(details) = path_error_details(e) {
        let e = details.original_io_error;
        let errno = io_error_errno(e);
        return cpython::PyErr::new::<exc::OSError, _>(
            py,
            (
                errno,
                io_error_strerror(e, errno),
                details.path.display().to_string(),
            ),
        );
    }

    let errno = io_error_errno(e);
    cpython::PyErr::new::<exc::OSError, _>(py, (errno, io_error_strerror(e, errno)))
}

fn io_error_strerror(e: &std::io::Error, errno: Option<i32>) -> String {
    let mut message = e.to_string();
    let Some(errno) = errno else {
        return message;
    };

    // Rust formats OS errors as "{sys_message} (os error {code})" internally.
    // Python OSError.strerror is just the `sys_message`, with errno.
    // Strip exactly the suffix Rust adds when it matches the errno.
    let suffix = format!(" (os error {errno})");
    if message.ends_with(&suffix) {
        message.truncate(message.len() - suffix.len());
        // Match CPython's Windows OSError behavior in
        // `Python/errors.c`'s `PyErr_SetExcFromWindowsErrWithFilenameObjects`:
        // FormatMessageW results have trailing whitespace and dots stripped
        // before becoming strerror.
        let len = message
            .trim_end_matches(|c: char| c.is_whitespace() || c == '.')
            .len();
        message.truncate(len);
    }
    message
}

fn io_error_errno(e: &std::io::Error) -> Option<i32> {
    if let Some(errno) = e.raw_os_error() {
        return Some(errno);
    }

    // Attempt to infer the errno from error type.
    //
    // This is useful for Python to test error type for io::Error generated by
    // non-syscalls. For example, pipe uses userspace pipe implementation and
    // can return BrokenPipe without errno.
    //
    // See rust's decode_error_kind for the reversed direction.
    use std::io::ErrorKind::*;
    match e.kind() {
        NotFound => Some(libc::ENOENT),
        PermissionDenied => Some(libc::EPERM),
        ConnectionRefused => Some(libc::ECONNREFUSED),
        ConnectionReset => Some(libc::ECONNRESET),
        ConnectionAborted => Some(libc::ECONNABORTED),
        NotConnected => Some(libc::ENOTCONN),
        AddrInUse => Some(libc::EADDRINUSE),
        AddrNotAvailable => Some(libc::EADDRNOTAVAIL),
        BrokenPipe => Some(libc::EPIPE),
        AlreadyExists => Some(libc::EEXIST),
        NotADirectory => Some(libc::ENOTDIR),
        IsADirectory => Some(libc::EISDIR),
        WouldBlock => Some(libc::EWOULDBLOCK),
        InvalidInput => Some(libc::EINVAL),
        TimedOut => Some(libc::ETIMEDOUT),
        Interrupted => Some(libc::EINTR),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use std::io;

    use cpython::ObjectProtocol;

    use super::*;

    #[test]
    fn test_io_error_subclasses() {
        let gil = Python::acquire_gil();
        let py = gil.python();

        for (kind, errno, exception_type) in [
            (
                io::ErrorKind::NotFound,
                Some(libc::ENOENT),
                py.get_type::<exc::FileNotFoundError>(),
            ),
            (
                io::ErrorKind::PermissionDenied,
                Some(libc::EPERM),
                py.get_type::<exc::PermissionError>(),
            ),
            (io::ErrorKind::Other, None, py.get_type::<exc::OSError>()),
        ] {
            let mut err = translate_io_error(py, &io::Error::new(kind, "test error"));
            // FIXME: specific I/O errors should match their built-in subclasses.
            assert!(err.matches(py, py.get_type::<exc::OSError>()));
            assert_eq!(
                err.matches(py, exception_type),
                kind == io::ErrorKind::Other
            );
            let value = err.instance(py);
            assert_eq!(
                value
                    .getattr(py, "errno")
                    .unwrap()
                    .extract::<Option<i32>>(py)
                    .unwrap(),
                errno,
            );
            assert_eq!(
                value
                    .getattr(py, "strerror")
                    .unwrap()
                    .extract::<String>(py)
                    .unwrap(),
                "test error",
            );
        }
    }

    #[cfg(windows)]
    #[test]
    fn test_windows_io_error_codes() {
        let gil = Python::acquire_gil();
        let py = gil.python();

        // ERROR_FILE_NOT_FOUND and ERROR_PATH_NOT_FOUND both map to ENOENT.
        for winerror in [2, 3] {
            let mut err = translate_io_error(py, &io::Error::from_raw_os_error(winerror));
            // FIXME: these errors should match FileNotFoundError immediately.
            assert!(err.matches(py, py.get_type::<exc::OSError>()));
            assert!(!err.matches(py, py.get_type::<exc::FileNotFoundError>()));
            let value = err.instance(py);
            // FIXME: translate the native code to ENOENT and preserve winerror.
            assert_eq!(
                value
                    .getattr(py, "errno")
                    .unwrap()
                    .extract::<i32>(py)
                    .unwrap(),
                winerror,
            );
            assert_eq!(
                value
                    .getattr(py, "winerror")
                    .unwrap()
                    .extract::<Option<i32>>(py)
                    .unwrap(),
                None,
            );
        }
    }
}
