/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

use cpython::Python;
use cpython::exc;
use util::path_error_details;

pub fn translate_io_error(py: Python, e: &std::io::Error) -> cpython::PyErr {
    if let Some(details) = path_error_details(e) {
        let e = details.original_io_error;
        let errno = io_error_errno(e);
        return cpython::PyErr::new::<exc::OSError, _>(
            py,
            (
                errno,
                io_error_strerror(e, errno),
                details.path.display().to_string(),
            ),
        );
    }

    let errno = io_error_errno(e);
    cpython::PyErr::new::<exc::OSError, _>(py, (errno, io_error_strerror(e, errno)))
}

fn io_error_strerror(e: &std::io::Error, errno: Option<i32>) -> String {
    let mut message = e.to_string();
    let Some(errno) = errno else {
        return message;
    };

    // Rust formats OS errors as "{sys_message} (os error {code})" internally.
    // Python OSError.strerror is just the `sys_message`, with errno.
    // Strip exactly the suffix Rust adds when it matches the errno.
    let suffix = format!(" (os error {errno})");
    if message.ends_with(&suffix) {
        message.truncate(message.len() - suffix.len());
    }
    message
}

fn io_error_errno(e: &std::io::Error) -> Option<i32> {
    if let Some(errno) = e.raw_os_error() {
        return Some(errno);
    }

    // Attempt to infer the errno from error type.
    //
    // This is useful for Python to test error type for io::Error generated by
    // non-syscalls. For example, pipe uses userspace pipe implementation and
    // can return BrokenPipe without errno.
    //
    // See rust's decode_error_kind for the reversed direction.
    use std::io::ErrorKind::*;
    match e.kind() {
        NotFound => Some(libc::ENOENT),
        PermissionDenied => Some(libc::EPERM),
        ConnectionRefused => Some(libc::ECONNREFUSED),
        ConnectionReset => Some(libc::ECONNRESET),
        ConnectionAborted => Some(libc::ECONNABORTED),
        NotConnected => Some(libc::ENOTCONN),
        AddrInUse => Some(libc::EADDRINUSE),
        AddrNotAvailable => Some(libc::EADDRNOTAVAIL),
        BrokenPipe => Some(libc::EPIPE),
        AlreadyExists => Some(libc::EEXIST),
        NotADirectory => Some(libc::ENOTDIR),
        IsADirectory => Some(libc::EISDIR),
        WouldBlock => Some(libc::EWOULDBLOCK),
        InvalidInput => Some(libc::EINVAL),
        TimedOut => Some(libc::ETIMEDOUT),
        Interrupted => Some(libc::EINTR),
        _ => None,
    }
}
