load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "time_measuring",
    srcs = glob([
        "src/**/*.rs",
    ]),
    test_deps = ["//eden/mononoke/mononoke_macros:mononoke_macros"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:dashmap",
        "fbsource//third-party/rust:thiserror",
    ],
)
