load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "topo_sort",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:maplit",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
    deps = [
    ],
)
