load("//fbpkg:fbpkg.bzl", "fbpkg")

oncall("scm_server_infra")

fbpkg.builder(
    name = "mononoke.shardmanager.test",
    path_actions = {
        "executor": "//eden/mononoke/tools/executor:executor",
    },
)
