load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("sapling")

rust_binary(
    name = "fsprobe",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:structopt",
    ],
)
