load("//eden/scm:targets.bzl", "sl_rust_binary")

oncall("sapling")

sl_rust_binary(
    name = "fsprobe",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
    ],
)
