load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("source_control")

thrift_library(
    name = "xdb_gc_structs",
    languages = [
        "python",
        "rust",
    ],
    py3_namespace = "configerator.mononoke",
    thrift_rust_options = "serde",
    thrift_srcs = {"xdb_gc.thrift": None},
    deps = [
        "//thrift/annotation:rust",
    ],
)
