load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup", "buck_sh_binary")
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")
load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

python_library(
    name = "lib_buck",
    srcs = ["lib_buck.py"],
)

python_library(
    name = "lib_runner",
    srcs = ["lib_runner.py"],
    deps = [
        "fbsource//third-party/pypi/click:click",
        "//common/db/tests:DbDef",
        "//configerator/distribution/api/py:configerator_client",
        "//configerator/structs/mysql:table_schema-py-deprecated",
        "//dba/ephemeral_shards/if:ephemeral_shards_thrift-py-deprecated",
        "//libfb/py:db_locator",
    ],
)

buck_filegroup(
    name = "facebook_test_fixtures",
    srcs = [
        "fb_library.sh",
        "git_pushrebase/library-git-pushrebase.sh",
        "verify_integrity_mocked_diff_info.json",
    ],
)

python_binary(
    name = "generate_manifest",
    srcs = ["generate_manifest.py"],
    main_function = "eden.mononoke.tests.integration.facebook.generate_manifest.main",
    deps = [
        ":lib_buck",
    ],
)

buck_sh_binary(
    name = "disable-all-network-access",
    main = "disable-all-network-access.sh",
)

dott_test(
    name = "backfill-bonsai-blob-mapping",
    dott_files = glob(["test-backfill-bonsai-blob-mapping-*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/facebook/backfill_bonsai_blob_mapping:backfill_bonsai_blob_mapping",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "gitbundle",
    dott_files = glob([
        "test-gitbundle*.t",
    ]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/git/facebook/git_move_bookmark:git_move_bookmark",
        "//eden/mononoke/git/facebook/remote_gitimport:remote_gitimport",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/lfs_server:lfs_server",
        "//eden/mononoke/scs/client:scsc",
        "//eden/mononoke/scs/scs_server:scs_server",
        "//eden/mononoke/tools/admin:admin",
    ],
)

dott_test(
    name = "repo_metadata_logger",
    dott_files = glob(["test-repo-metadata-logger-*.t"]),
    deps = [
        "//eden/mononoke/tools/facebook/repo_metadata_logger:repo_metadata_logger",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "server",
    disable_all_network_access_target = True,
    dott_files = glob(
        [
            "test-metadata*.t",
            "test-untrusted-env*.t",
        ],
        exclude = [
            "test-metadata-fb-host.t",
            "test-metadata.t",
        ],
    ) + [
        "test-per-repo-acl.t",
        "test-post-push-logging-identities.t",
        "test-readonly-server.t",
        "test-server.t",
        "test-server-mononokepeer-proxy.t",
    ],
    deps = [
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "server-needs-network",
    dott_files = [
        # Purposely not disabling network as this tests reverse dns lookups
        "test-metadata-fb-host.t",
        "test-metadata.t",
        # Purposely not disabling network as this needs to make TLS connections.
        "test-cat-auth.t",
    ],
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "slow-bookmark-mover",
    dott_files = glob([
        "test-mononoke-slow-bookmark-mover*.t",
    ]),
    deps = [
        "//eden/mononoke:bonsai_verify",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/facebook/slow_bookmark_mover:slow_bookmark_mover",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "sql-telemetry",
    dott_files = ["test-sql-telemetry.t"],
    use_mysql = True,
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "test-bookmark-service",
    dott_files = glob(["test-bookmark-service*.t"]),
    deps = [
        "//eden/mononoke/facebook/bookmark_service:bookmark_service_client_cli",
        "//eden/mononoke/facebook/bookmark_service:bookmark_service_server",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "test-server-and-bookmark-service",
    dott_files = glob(["test-server-and-bookmark-service-*.t"]),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/facebook/bookmark_service:bookmark_service_client_cli",
        "//eden/mononoke/facebook/bookmark_service:bookmark_service_server",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)

dott_test(
    name = "tools-example",
    dott_files = glob([
        "test-tools-example*.t",
    ]),
    deps = [
        "//eden/mononoke/tools/example:example",
    ],
)

dott_test(
    name = "verify-integrity",
    dott_files = [
        "test-hook-verify-integrity.t",
    ],
    deps = [
        "//common/tools/thriftdbg:thriftdbg",
        "//eden/mononoke:blobimport",
        "//eden/mononoke:mononoke",
        "//eden/mononoke/tools/testtool:testtool",
        "//security/source_control/verify_integrity:verify_integrity",
        "//security/source_control/verify_integrity/service:verify_integrity_service",
    ],
)
