load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")
load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "backtrace-python-offset-probe",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "description": "Attmpt to obtain raw offsets used to extract Python frames. Intended to be used at build time.",
                "homepage": "https://sapling-scm.com/",
                "license": "MIT",
                "name": "sapling-backtrace-python-offset-probe",
                "repository": "https://github.com/facebook/sapling",
            },
        },
    },
    deps = [
        "fbsource//third-party/rust:backtrace",
        "fbsource//third-party/rust:libc",
        "//eden/scm/lib/backtrace-python/evalframe-sys:evalframe-sys",
    ],
)

rust_binary(
    name = "offset-codegen",
    srcs = ["src/bin/offset-codegen.rs"],
    crate_root = "src/bin/offset-codegen.rs",
    deps = [
        ":backtrace-python-offset-probe",
    ],
)
