load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pyio",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/io:io",
        "//eden/scm/lib/io/term/style:termstyle",
        "//eden/scm/saplingnative/bindings/modules/pyconfigloader:pyconfigloader",
    ],
)
