load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "logger_ext",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/server/context:context",
    ],
)
