load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("sapling")

rust_binary(
    name = "virtual-tree-benches",
    srcs = glob([
        "src/**/*.rs",
    ]),
    crate_root = "src/main.rs",
    deps = [
        "//eden/scm/lib/minibench:minibench",
        "//eden/scm/lib/virtual-repo/virtual-tree:virtual-tree",
    ],
)
