load("//eden/scm:targets.bzl", "sl_rust_library")

oncall("sapling")

sl_rust_library(
    name = "win32-8dot3",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_toml_config": {
            "lib": {"name": "win32_8dot3"},
            "package": {
                "authors": ["Meta Source Control Team <sourcecontrol-dev@meta.com>"],
                "homepage": "https://sapling-scm.com/",
                "license": "MIT",
                "name": "sapling-win32-8dot3",
                "repository": "https://github.com/facebook/sapling",
            },
        },
    },
    crate_root = "src/lib.rs",
    test_deps = [
        "fbsource//third-party/rust:tempfile",
    ],
    deps = select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "fbsource//third-party/rust:winapi",
        ],
    }),
)
