load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "git-pool",
    srcs = glob([
        "src/**/*.rs",
    ]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:git2",
        "fbsource//third-party/rust:num_cpus",
        "fbsource//third-party/rust:r2d2",
        "fbsource//third-party/rust:tokio",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
)
