load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "async_limiter",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_toml_config": {
            "package": {
                "autoexamples": False,
            },
        },
    },
    test_deps = [
        "fbsource//third-party/rust:nonzero_ext",
        "fbsource//third-party/rust:tokio",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:governor",
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
    ],
)
