load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("scm_client_infra")

cpp_unittest(
    name = "test",
    srcs = glob(["*Test.cpp"]),
    network_access = network_access_utils.none(),
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//eden/common/telemetry:structured_logger",
        "//eden/common/utils:path",
        "//eden/common/utils:process_info_cache",
        "//eden/fs/config:config",
        "//eden/fs/model:model",
        "//eden/fs/store:backing_store_interface",
        "//eden/fs/store:store",
        "//eden/fs/store/filter:filtered_object_id",
        "//eden/fs/store/filter:glob_filter",
        "//eden/fs/testharness:fake_backing_store_and_tree_builder",
        "//folly:range",
        "//folly/executors:manual_executor",
    ],
)
