load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_client_infra")

rust_library(
    name = "edenfs-core",
    srcs = glob(["src/**/*.rs"]),
    named_deps = {
        "hg_util": "//eden/scm/lib/util:util",
    },
    test_deps = [
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:serde_test",
        "fbsource//third-party/rust:tempfile",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-recursion",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:byteorder",
        "fbsource//third-party/rust:dirs",
        "fbsource//third-party/rust:dunce",
        "fbsource//third-party/rust:rayon",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:shlex",
        "fbsource//third-party/rust:strum",
        "fbsource//third-party/rust:subprocess",
        "fbsource//third-party/rust:sysinfo",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:toml",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:uuid",
        "//common/rust/shed/fbthrift_ext:socket",
        "//common/rust/shed/tokio-uds-compat:tokio-uds-compat",
        "//eden/fs/cli_rs/edenfs-config:edenfs-config",
        "//eden/fs/cli_rs/edenfs-error:edenfs-error",
        "//eden/fs/cli_rs/edenfs-utils:edenfs-utils",
        "//eden/scm/lib/atomicfile:atomicfile",
        "//eden/scm/lib/thrift-types:thrift-types",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:libc",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:libc",
            "fbsource//third-party/rust:psutil",
            "//eden/scm/exec/eden_apfs_mount_helper:eden_apfs",
        ],
        "ovr_config//os:windows": [
            "//eden/scm/exec/scratch:mkscratch",
        ],
    }),
)
