load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_client_infra")

rust_library(
    name = "edenfs-core",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//common/rust/shed/fbthrift_ext:socket",
        "//common/rust/shed/tokio-uds-compat:tokio-uds-compat",
        "//eden/fs/cli_rs/edenfs-utils:edenfs-utils",
        "//eden/scm/lib/thrift-types:thrift-types",
    ],
)
