load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_infra")

rust_library(
    name = "rate_limiting",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "//eden/mononoke/mononoke_macros:mononoke_macros",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:strum",
        "fbsource//third-party/rust:thiserror",
        "fbsource//third-party/rust:tokio",
        "//common/rust/fbwhoami:fbwhoami",
        "//common/rust/ratelim:ratelim",
        "//common/rust/shed/cached_config:cached_config",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/stats:stats",
        "//configerator/structs/scm/mononoke/ratelimiting:rate_limiting_config-rust",
        "//eden/mononoke/common/ods_counters:ods_counters",
        "//eden/mononoke/common/scuba_ext:scuba_ext",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
        "//eden/mononoke/permission_checker:permission_checker",
    ],
)
