load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

dott_test(
    name = "walker",
    dott_files = glob(["*.t"]),
    deps = [
        "//eden/mononoke/jobs/walker:walker",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/blobimport:blobimport",
        "//eden/mononoke/tools/packer:packer",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
