load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("scm_client_infra")

cpp_library(
    name = "meminodecatalog",
    srcs = [
        "MemInodeCatalog.cpp",
    ],
    headers = [
        "MemInodeCatalog.h",
    ],
    deps = select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "//eden/fs/inodes/overlay:windows_fsck",
        ],
    }),
    exported_deps = [
        "//eden/fs/inodes:inode_catalog",
        "//eden/fs/inodes:inode_number",
        "//folly/container:f14_hash",
    ],
)
