load("@fbcode_macros//build_defs/lib:rust_oss.bzl", "rust_oss")
load(
    "//eden/mononoke/tests/integration/facebook:fb_manifest_deps.bzl",
    "dott_test",
)

oncall("scm_server_treehugger")

# Tests that require features not available in OSS builds (e.g., jemalloc profiling)
OSS_EXCLUDED_TESTS = [
    "test-mononoke-git-server-flamegraph.t",
]

dott_test(
    name = "mononoke-git-server",
    # These tests have been vetted to run well without network access. Please investigate any failure thoroughly before disabling.
    disable_all_network_access_target = True,
    dott_files =
        glob(
            ["*.t"],
            exclude = OSS_EXCLUDED_TESTS if rust_oss.is_oss_build() else [],
        ),
    deps = [
        "//eden/mononoke:mononoke",
        "//eden/mononoke/features/commit_rewriting/mononoke_x_repo_sync_job:mononoke_x_repo_sync_job",
        "//eden/mononoke/git/gitimport:gitimport",
        "//eden/mononoke/servers/git/git_server:git_server",
        "//eden/mononoke/servers/lfs/lfs_server:lfs_server",
        "//eden/mononoke/tools/admin:admin",
        "//eden/mononoke/tools/testtool:testtool",
    ],
)
