# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  # Debian 8.1 x86_64 without configuration management software
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "tests"

  config.vm.define "tests" do |conf|
    conf.vm.provision :file, source: "run-tests.sh", destination:"run-tests.sh"
    conf.vm.provision :shell, path: "provision.sh"
    conf.vm.synced_folder "../..", "/hgshared"
  end
end
