load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs:rust_unittest.bzl", "rust_unittest")

oncall("scm_server_treehugger")

rust_library(
    name = "bonsai_p4_mapping",
    srcs = glob([
        "src/**/*.rs",
        "schemas/**/*.sql",
    ]),
    test_deps = [
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
        "//eden/mononoke/mononoke_types:mononoke_types-mocks",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bincode",
        "fbsource//third-party/rust:bytes",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/memcache_stub:memcache",
        "//eden/mononoke/common/rust/caching_ext:caching_ext",
        "//eden/mononoke/common/rust/sql_ext:sql_ext",
        "//eden/mononoke/common/sql_construct:sql_construct",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/bonsai_p4_mapping/if:bonsai_p4_mapping_thrift-rust",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
        "//thrift/lib/rust:fbthrift",
    ],
)

rust_unittest(
    name = "bonsai_p4_mapping_test",
    srcs = glob(["test/**/*.rs"]),
    crate = "bonsai_p4_mapping_test",
    deps = [
        "fbsource//third-party/rust:anyhow",
        ":bonsai_p4_mapping",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
        "//eden/mononoke/common/sql_construct:sql_construct",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/mononoke_types:mononoke_types-mocks",
        "//eden/mononoke/repo_factory:test_repo_factory",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
    ],
)
