load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "codegen",
    srcs = [
        "src/codegen.rs",
        "src/lib.rs",
        "src/pycompile.py",
    ],
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/zstdelta:zstdelta",
    ],
)
