load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("sapling")

rust_binary(
    name = "codegen",
    srcs = [
        "src/codegen.rs",
        "src/main.rs",
        "src/pycompile.py",
    ],
    crate_root = "src/main.rs",
    deps = [
        "//eden/scm/lib/zstdelta:zstdelta",
    ],
)
