load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("sapling")

rust_library(
    name = "codegen",
    srcs = [
        "src/codegen.rs",
        "src/lib.rs",
        "src/pycompile.py",
    ],
    crate_root = "src/lib.rs",
    deps = [
        "//eden/scm/lib/zstdelta:zstdelta",
    ],
)
