load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")

oncall("scm_server_infra")

rust_binary(
    name = "sqlblob_gc",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:bytesize",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tracing",
        "//common/rust/shed/fbinit:fbinit",
        "//common/rust/shed/futures_retry:futures_retry",
        "//eden/mononoke/blobstore:blobstore_factory",
        "//eden/mononoke/blobstore:sqlblob",
        "//eden/mononoke/cmdlib:cmdlib_logging",
        "//eden/mononoke/cmdlib/mononoke_app:mononoke_app",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_macros:mononoke_macros",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
    ],
)
