load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_client_infra")

rust_library(
    name = "edenfs-saved-state",
    srcs = glob(["src/**/*.rs"]),
    compatible_with = [
        "ovr_config//os:linux",
    ],
    test_deps = [
        "//common/rust/mysql:ephemeral_shards",
        "//common/rust/shed/fbinit:fbinit-tokio",
    ],
    test_labels = ["needs_local_mysqld"],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:thiserror",
        "//common/rust/mysql:mysql_client",
        "//common/rust/shed/fbinit:fbinit",
        "//eden/fs/cli_rs/sapling-client:sapling-client",
    ],
)
