load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_server_treehugger")

rust_library(
    name = "derivation_pipeline_test_harness",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {"cargo_toml_dir": "."},
    test_deps = [
        "//common/rust/shed/fbinit:fbinit-tokio",
        "//eden/mononoke/common/mononoke_macros:mononoke_macros",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:futures",
        "//common/rust/shed/facet:facet",
        "//common/rust/shed/fbinit:fbinit",
        "//eden/mononoke/blobstore:blobstore",
        "//eden/mononoke/common/rust/justknobs_ext:justknobs",
        "//eden/mononoke/derived_data:bulk_derivation",
        "//eden/mononoke/derived_data:derived_data_manager",
        "//eden/mononoke/derived_data/derivation_pipeline_utils:derivation_pipeline_utils",
        "//eden/mononoke/metaconfig:metaconfig_types",
        "//eden/mononoke/mononoke_types:mononoke_types",
        "//eden/mononoke/repo_attributes/bonsai_hg_mapping:bonsai_hg_mapping",
        "//eden/mononoke/repo_attributes/bookmarks:bookmarks",
        "//eden/mononoke/repo_attributes/commit_graph/commit_graph:commit_graph",
        "//eden/mononoke/repo_attributes/filestore:filestore",
        "//eden/mononoke/repo_attributes/repo_blobstore:repo_blobstore",
        "//eden/mononoke/repo_attributes/repo_derived_data:repo_derived_data",
        "//eden/mononoke/repo_attributes/repo_identity:repo_identity",
        "//eden/mononoke/servers/slapi/slapi_server/context:context",
        "//eden/mononoke/tests/fixtures:fixtures",
    ],
)
