name: Mononoke CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
    - name: Build dependencies
      run: python3 build/fbcode_builder/getdeps.py build --only-deps --src-dir=. mononoke
    - name: Build mononoke
      run: python3 build/fbcode_builder/getdeps.py build --no-deps --src-dir=. mononoke
    - name: Copy artifacts
      run: python3 build/fbcode_builder/getdeps.py fixup-dyn-deps --src-dir=. mononoke _artifacts/linux
    - uses: actions/upload-artifact@master
      with:
        name: mononoke
        path: _artifacts
    - name: Test mononoke
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
    - name: Install Rust Beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true
        profile: minimal
    - name: Test mononoke with beta toolchain
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
      continue-on-error: true
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
    - name: Test mononoke with nightly toolchain
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
      continue-on-error: true
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
    - name: Build dependencies
      run: python3 build/fbcode_builder/getdeps.py build --only-deps --src-dir=. mononoke
    - name: Build mononoke
      run: python3 build/fbcode_builder/getdeps.py build --no-deps --src-dir=. mononoke
    - name: Copy artifacts
      run: python3 build/fbcode_builder/getdeps.py fixup-dyn-deps --src-dir=. mononoke _artifacts/mac
    - uses: actions/upload-artifact@master
      with:
        name: mononoke
        path: _artifacts
    - name: Test mononoke
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
    - name: Install Rust Beta
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        default: true
        profile: minimal
    - name: Test mononoke with beta toolchain
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
      continue-on-error: true
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal
    - name: Test mononoke with nightly toolchain
      run: python3 build/fbcode_builder/getdeps.py test --src-dir=. mononoke
      continue-on-error: true
