name: CI - Ubuntu 20.04
'on': workflow_dispatch
jobs:
  build-deb:
    runs-on: ubuntu-latest
    container:
      image: ${{ format('ghcr.io/{0}/build_ubuntu_20_04:latest', github.repository) }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: rustup
      run: rustup default stable
    - name: set-env DEB_UPSTREAM_VERSION
      shell: bash
      run: echo "DEB_UPSTREAM_VERSION=$(ci/tag-name.sh | tr \- .)" >> $GITHUB_ENV
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=$(ci/tag-name.sh | tr \- .)" >> $GITHUB_ENV
    - name: Create .deb
      working-directory: ./eden/scm
      run: ${{ format('VERSION=0.0-{0} make deb', env.DEB_UPSTREAM_VERSION) }}
    - name: Rename .deb
      working-directory: ./eden/scm
      run: ${{ format('mv sapling_0.0-{0}_amd64.deb sapling_0.0-{0}_amd64.Ubuntu20.04.deb', env.DEB_UPSTREAM_VERSION, env.DEB_UPSTREAM_VERSION) }}
