name: Verify addons/ folder
env:
  CI: false

on: {}

jobs:
  verify-addons:
    runs-on: ubuntu-latest
    # Our build container already has Node, Yarn, and Python installed.
    container:
      image: ${{ format('ghcr.io/{0}/build_ubuntu_22_04:latest', github.repository) }}
    steps:
      - name: Install fb-watchman
        run: curl -fsSL https://github.com/facebook/watchman/releases/download/v2023.09.18.00/watchman_ubuntu20.04_v2023.09.18.00.deb -o watchman.deb && apt -y -f install ./watchman.deb
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Grant Access
        run: git config --global --add safe.directory "$PWD"
      - name: yarn install
        working-directory: ./addons
        run: yarn install --prefer-offline
      - name: Run addons/verify-addons-folder.py
        working-directory: ./addons
        run: ./verify-addons-folder.py --skip-integration-tests
