name: Docker Image - ubuntu:20.04
'on':
  workflow_dispatch: null
  schedule:
  - cron: 0 1 * * mon
jobs:
  clone-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .github/workflows/sapling-cli-ubuntu-20.04.Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ format('ghcr.io/{0}/build_ubuntu_20_04:latest', github.repository) }}
