load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("scm_client_infra")

rust_library(
    name = "edenfs-asserted-states",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:lazy_static",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:whoami",
        "//eden/fs/cli_rs/edenfs-client:edenfs-client",
        "//eden/fs/cli_rs/edenfs-error:edenfs-error",
        "//eden/fs/rust/edenfs-asserted-states-client:edenfs-asserted-states-client",
        "//eden/fs/rust/facebook/edenfs-telemetry:edenfs-telemetry",
        "//eden/scm/lib/util:util",
    ],
)
